// Generated by `pnpm codegen` from errors/*.json. Do not edit manually.

import * as Data from "effect/Data";
import * as Schema from "effect/Schema";

/** Token segment is empty or not in bot id:hash form */

export class NotFound extends Data.TaggedError("NotFound")<{
	readonly description: string;
}> {}

export const NotFoundError = Schema.TaggedStruct("NotFound", {
	description: Schema.String,
});

/** Token has bot id:hash form but the secret is invalid */

export class Unauthorized extends Data.TaggedError("Unauthorized")<{
	readonly description: string;
}> {}

export const UnauthorizedError = Schema.TaggedStruct("Unauthorized", {
	description: Schema.String,
});

export const methodErrors = {
	getMe: {
		401: Unauthorized,
		404: NotFound,
	},
} as const;
