// Generated by `pnpm codegen` from errors/*.json. Do not edit manually.

import * as Data from "effect/Data";
import * as Schema from "effect/Schema";

/** chat_id parameter is missing or empty */

export class ChatIdEmpty extends Data.TaggedError("ChatIdEmpty")<{
	readonly description: string;
}> {}

export const ChatIdEmptyError = Schema.TaggedStruct("ChatIdEmpty", {
	description: Schema.String,
});

/** chat_id does not refer to a chat the bot can access (unknown numeric id or unresolvable @username) */

export class ChatNotFound extends Data.TaggedError("ChatNotFound")<{
	readonly description: string;
}> {}

export const ChatNotFoundError = Schema.TaggedStruct("ChatNotFound", {
	description: Schema.String,
});

/** file_id is not valid */

export class InvalidFileId extends Data.TaggedError("InvalidFileId")<{
	readonly description: string;
}> {}

export const InvalidFileIdError = Schema.TaggedStruct("InvalidFileId", {
	description: Schema.String,
});

/** text is missing or empty */

export class MessageTextEmpty extends Data.TaggedError("MessageTextEmpty")<{
	readonly description: string;
}> {}

export const MessageTextEmptyError = Schema.TaggedStruct("MessageTextEmpty", {
	description: Schema.String,
});

/** Token segment is empty or not in bot id:hash form */

export class NotFound extends Data.TaggedError("NotFound")<{
	readonly description: string;
}> {}

export const NotFoundError = Schema.TaggedStruct("NotFound", {
	description: Schema.String,
});

/** Token has bot id:hash form but the secret is invalid */

export class Unauthorized extends Data.TaggedError("Unauthorized")<{
	readonly description: string;
}> {}

export const UnauthorizedError = Schema.TaggedStruct("Unauthorized", {
	description: Schema.String,
});

export const methodErrors = {
	getAvailableGifts: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getChat: [
		{ errorCode: 400, description: "Bad Request: chat_id is empty", error: ChatIdEmpty },
		{ errorCode: 400, description: "Bad Request: chat not found", error: ChatNotFound },
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getFile: [
		{ errorCode: 400, description: "Bad Request: invalid file_id", error: InvalidFileId },
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getForumTopicIconStickers: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getMe: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getMyCommands: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getMyDefaultAdministratorRights: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getMyDescription: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getMyName: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	getMyShortDescription: [
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
	sendMessage: [
		{ errorCode: 400, description: "Bad Request: message text is empty", error: MessageTextEmpty },
		{ errorCode: 404, description: "Not Found", error: NotFound },
		{ errorCode: 401, description: "Unauthorized: invalid token specified", error: Unauthorized },
	],
} as const;
