// Generated by `pnpm codegen` from spec/errors/errors.json and spec/errors/{method}.json. Do not edit manually.

import * as Data from "effect/Data";
import * as Schema from "effect/Schema";

/**
 * Raised when Telegram responds with `{ "ok": false }` and the failure is not documented for the method.
 */
export class TelegramApiError extends Data.TaggedError("TelegramApiError")<{
	readonly errorCode: number;
	readonly description: string;
}> {}

export class BadRequest extends Data.TaggedError("BadRequest")<{
	readonly ok: false;
	readonly error_code: 400;
	readonly description: string;
}> {}

export const BadRequestError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(400),
	description: Schema.String,
});

/**
 * Token has bot id:hash form but the secret is invalid
 */
export class Unauthorized extends Data.TaggedError("Unauthorized")<{
	readonly ok: false;
	readonly error_code: 401;
	readonly description: string;
}> {}

/**
 * Token has bot id:hash form but the secret is invalid
 */
export const UnauthorizedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(401),
	description: Schema.String,
});

export class PaymentRequired extends Data.TaggedError("PaymentRequired")<{
	readonly ok: false;
	readonly error_code: 402;
	readonly description: string;
}> {}

export const PaymentRequiredError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(402),
	description: Schema.String,
});

export class Forbidden extends Data.TaggedError("Forbidden")<{
	readonly ok: false;
	readonly error_code: 403;
	readonly description: string;
}> {}

export const ForbiddenError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(403),
	description: Schema.String,
});

/**
 * Token segment is empty or not in bot id:hash form
 */
export class NotFound extends Data.TaggedError("NotFound")<{
	readonly ok: false;
	readonly error_code: 404;
	readonly description: string;
}> {}

/**
 * Token segment is empty or not in bot id:hash form
 */
export const NotFoundError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(404),
	description: Schema.String,
});

export class MethodNotAllowed extends Data.TaggedError("MethodNotAllowed")<{
	readonly ok: false;
	readonly error_code: 405;
	readonly description: string;
}> {}

export const MethodNotAllowedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(405),
	description: Schema.String,
});

export class NotAcceptable extends Data.TaggedError("NotAcceptable")<{
	readonly ok: false;
	readonly error_code: 406;
	readonly description: string;
}> {}

export const NotAcceptableError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(406),
	description: Schema.String,
});

export class ProxyAuthenticationRequired extends Data.TaggedError("ProxyAuthenticationRequired")<{
	readonly ok: false;
	readonly error_code: 407;
	readonly description: string;
}> {}

export const ProxyAuthenticationRequiredError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(407),
	description: Schema.String,
});

export class RequestTimeout extends Data.TaggedError("RequestTimeout")<{
	readonly ok: false;
	readonly error_code: 408;
	readonly description: string;
}> {}

export const RequestTimeoutError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(408),
	description: Schema.String,
});

export class Conflict extends Data.TaggedError("Conflict")<{
	readonly ok: false;
	readonly error_code: 409;
	readonly description: string;
}> {}

export const ConflictError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(409),
	description: Schema.String,
});

export class Gone extends Data.TaggedError("Gone")<{
	readonly ok: false;
	readonly error_code: 410;
	readonly description: string;
}> {}

export const GoneError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(410),
	description: Schema.String,
});

export class LengthRequired extends Data.TaggedError("LengthRequired")<{
	readonly ok: false;
	readonly error_code: 411;
	readonly description: string;
}> {}

export const LengthRequiredError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(411),
	description: Schema.String,
});

export class PreconditionFailed extends Data.TaggedError("PreconditionFailed")<{
	readonly ok: false;
	readonly error_code: 412;
	readonly description: string;
}> {}

export const PreconditionFailedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(412),
	description: Schema.String,
});

export class PayloadTooLarge extends Data.TaggedError("PayloadTooLarge")<{
	readonly ok: false;
	readonly error_code: 413;
	readonly description: string;
}> {}

export const PayloadTooLargeError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(413),
	description: Schema.String,
});

export class UriTooLong extends Data.TaggedError("UriTooLong")<{
	readonly ok: false;
	readonly error_code: 414;
	readonly description: string;
}> {}

export const UriTooLongError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(414),
	description: Schema.String,
});

export class UnsupportedMediaType extends Data.TaggedError("UnsupportedMediaType")<{
	readonly ok: false;
	readonly error_code: 415;
	readonly description: string;
}> {}

export const UnsupportedMediaTypeError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(415),
	description: Schema.String,
});

export class RangeNotSatisfiable extends Data.TaggedError("RangeNotSatisfiable")<{
	readonly ok: false;
	readonly error_code: 416;
	readonly description: string;
}> {}

export const RangeNotSatisfiableError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(416),
	description: Schema.String,
});

export class ExpectationFailed extends Data.TaggedError("ExpectationFailed")<{
	readonly ok: false;
	readonly error_code: 417;
	readonly description: string;
}> {}

export const ExpectationFailedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(417),
	description: Schema.String,
});

export class ImATeapot extends Data.TaggedError("ImATeapot")<{
	readonly ok: false;
	readonly error_code: 418;
	readonly description: string;
}> {}

export const ImATeapotError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(418),
	description: Schema.String,
});

export class MisdirectedRequest extends Data.TaggedError("MisdirectedRequest")<{
	readonly ok: false;
	readonly error_code: 421;
	readonly description: string;
}> {}

export const MisdirectedRequestError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(421),
	description: Schema.String,
});

export class UnprocessableContent extends Data.TaggedError("UnprocessableContent")<{
	readonly ok: false;
	readonly error_code: 422;
	readonly description: string;
}> {}

export const UnprocessableContentError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(422),
	description: Schema.String,
});

export class Locked extends Data.TaggedError("Locked")<{
	readonly ok: false;
	readonly error_code: 423;
	readonly description: string;
}> {}

export const LockedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(423),
	description: Schema.String,
});

export class FailedDependency extends Data.TaggedError("FailedDependency")<{
	readonly ok: false;
	readonly error_code: 424;
	readonly description: string;
}> {}

export const FailedDependencyError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(424),
	description: Schema.String,
});

export class TooEarly extends Data.TaggedError("TooEarly")<{
	readonly ok: false;
	readonly error_code: 425;
	readonly description: string;
}> {}

export const TooEarlyError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(425),
	description: Schema.String,
});

export class UpgradeRequired extends Data.TaggedError("UpgradeRequired")<{
	readonly ok: false;
	readonly error_code: 426;
	readonly description: string;
}> {}

export const UpgradeRequiredError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(426),
	description: Schema.String,
});

export class PreconditionRequired extends Data.TaggedError("PreconditionRequired")<{
	readonly ok: false;
	readonly error_code: 428;
	readonly description: string;
}> {}

export const PreconditionRequiredError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(428),
	description: Schema.String,
});

export class TooManyRequests extends Data.TaggedError("TooManyRequests")<{
	readonly ok: false;
	readonly error_code: 429;
	readonly description: string;
}> {}

export const TooManyRequestsError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(429),
	description: Schema.String,
});

export class RequestHeaderFieldsTooLarge extends Data.TaggedError("RequestHeaderFieldsTooLarge")<{
	readonly ok: false;
	readonly error_code: 431;
	readonly description: string;
}> {}

export const RequestHeaderFieldsTooLargeError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(431),
	description: Schema.String,
});

export class UnavailableForLegalReasons extends Data.TaggedError("UnavailableForLegalReasons")<{
	readonly ok: false;
	readonly error_code: 451;
	readonly description: string;
}> {}

export const UnavailableForLegalReasonsError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(451),
	description: Schema.String,
});

export class InternalServerError extends Data.TaggedError("InternalServerError")<{
	readonly ok: false;
	readonly error_code: 500;
	readonly description: string;
}> {}

export const InternalServerErrorError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(500),
	description: Schema.String,
});

export class NotImplemented extends Data.TaggedError("NotImplemented")<{
	readonly ok: false;
	readonly error_code: 501;
	readonly description: string;
}> {}

export const NotImplementedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(501),
	description: Schema.String,
});

export class BadGateway extends Data.TaggedError("BadGateway")<{
	readonly ok: false;
	readonly error_code: 502;
	readonly description: string;
}> {}

export const BadGatewayError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(502),
	description: Schema.String,
});

export class ServiceUnavailable extends Data.TaggedError("ServiceUnavailable")<{
	readonly ok: false;
	readonly error_code: 503;
	readonly description: string;
}> {}

export const ServiceUnavailableError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(503),
	description: Schema.String,
});

export class GatewayTimeout extends Data.TaggedError("GatewayTimeout")<{
	readonly ok: false;
	readonly error_code: 504;
	readonly description: string;
}> {}

export const GatewayTimeoutError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(504),
	description: Schema.String,
});

export class HttpVersionNotSupported extends Data.TaggedError("HttpVersionNotSupported")<{
	readonly ok: false;
	readonly error_code: 505;
	readonly description: string;
}> {}

export const HttpVersionNotSupportedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(505),
	description: Schema.String,
});

export class VariantAlsoNegotiates extends Data.TaggedError("VariantAlsoNegotiates")<{
	readonly ok: false;
	readonly error_code: 506;
	readonly description: string;
}> {}

export const VariantAlsoNegotiatesError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(506),
	description: Schema.String,
});

export class InsufficientStorage extends Data.TaggedError("InsufficientStorage")<{
	readonly ok: false;
	readonly error_code: 507;
	readonly description: string;
}> {}

export const InsufficientStorageError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(507),
	description: Schema.String,
});

export class LoopDetected extends Data.TaggedError("LoopDetected")<{
	readonly ok: false;
	readonly error_code: 508;
	readonly description: string;
}> {}

export const LoopDetectedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(508),
	description: Schema.String,
});

export class NotExtended extends Data.TaggedError("NotExtended")<{
	readonly ok: false;
	readonly error_code: 510;
	readonly description: string;
}> {}

export const NotExtendedError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(510),
	description: Schema.String,
});

export class NetworkAuthenticationRequired extends Data.TaggedError("NetworkAuthenticationRequired")<{
	readonly ok: false;
	readonly error_code: 511;
	readonly description: string;
}> {}

export const NetworkAuthenticationRequiredError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Literal(511),
	description: Schema.String,
});

/**
 * Catch-all wire schema for undocumented `{ "ok": false }` responses.
 */
export const TelegramApiFailureError = Schema.Struct({
	ok: Schema.Literal(false),
	error_code: Schema.Number,
	description: Schema.String,
});
