// Generated by `pnpm codegen` from data/spec. Do not edit manually.
export * as Telegram from "./Telegram.ts";
export { callMethod, withToken } from "./Telegram.ts";
export * as Errors from "./Errors.ts";
export * as Methods from "./Methods.ts";
export * as Objects from "./Objects.ts";
