// Generated by `pnpm codegen` from data/spec. Do not edit manually.

import * as Schema from "effect/Schema";
import * as Rpc from "effect/unstable/rpc/Rpc";
import * as RpcGroup from "effect/unstable/rpc/RpcGroup";
import * as Errors from "./Errors.ts";
import * as Objects from "./Objects.ts";

/** Use this method to send answers to callback queries sent from inline keyboards. The answer will be displayed to the user as a notification at the top of the chat screen or as an alert. On success, True */
export const answerCallbackQuery = Rpc.make("answerCallbackQuery", {
	payload: {
		callback_query_id: Schema.String,
		text: Schema.optional(Schema.String),
		show_alert: Schema.optional(Schema.Boolean),
		url: Schema.optional(Schema.String),
		cache_time: Schema.optional(Schema.Int),
	},
	success: Schema.Literal(true),
});

/** Use this method to reply to a received guest message. On success, a SentGuestMessage object */
export const answerGuestQuery = Rpc.make("answerGuestQuery", {
	payload: {
		guest_query_id: Schema.String,
		result: Objects.InlineQueryResult,
	},
	success: Objects.SentGuestMessage,
});

/** Use this method to set the result of an interaction with a Web App and send a corresponding message on behalf of the user to the chat from which the query originated. On success, a SentWebAppMessage object */
export const answerWebAppQuery = Rpc.make("answerWebAppQuery", {
	payload: {
		web_app_query_id: Schema.String,
		result: Objects.InlineQueryResult,
	},
	success: Objects.SentWebAppMessage,
});

/** Use this method to approve a chat join request. The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right */
export const approveChatJoinRequest = Rpc.make("approveChatJoinRequest", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to ban a user in a group, a supergroup or a channel. In the case of supergroups and channels, the user will not be able to return to the chat on their own using invite links, etc., unless unbanned first. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const banChatMember = Rpc.make("banChatMember", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
		until_date: Schema.optional(Schema.Int),
		revoke_messages: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Use this method to ban a channel chat in a supergroup or a channel. Until the chat is unbanned, the owner of the banned chat won't be able to send messages on behalf of any of their channels. The bot must be an administrator in the supergroup or channel for this to work and must have the appropriate administrator rights */
export const banChatSenderChat = Rpc.make("banChatSenderChat", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		sender_chat_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to close the bot instance before moving it from one local server to another. You need to delete the webhook before calling this method to ensure that the bot isn't launched again after server restart. The method will return error 429 in the first 10 minutes after the bot is launched */
export const close = Rpc.make("close", {
	success: Schema.Literal(true),
});

/** Use this method to close an open topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic */
export const closeForumTopic = Rpc.make("closeForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to close an open 'General' topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights */
export const closeGeneralForumTopic = Rpc.make("closeGeneralForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Converts a given regular gift to Telegram Stars. Requires the can_convert_gifts_to_stars business bot right */
export const convertGiftToStars = Rpc.make("convertGiftToStars", {
	payload: {
		business_connection_id: Schema.String,
		owned_gift_id: Schema.String,
	},
	success: Schema.Literal(true),
});

/** Use this method to copy messages of any kind. Service messages, paid media messages, giveaway messages, giveaway winners messages, and invoice messages can't be copied. A quiz poll can be copied only if the value of the field correct_option_id is known to the bot. The method is analogous to the method forwardMessage, but the copied message doesn't have a link to the original message */
export const copyMessage = Rpc.make("copyMessage", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		from_chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_id: Schema.Int,
		video_start_timestamp: Schema.optional(Schema.Int),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		show_caption_above_media: Schema.optional(Schema.Boolean),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.MessageId,
});

/** Use this method to copy messages of any kind. If some of the specified messages can't be found or copied, they are skipped. Service messages, paid media messages, giveaway messages, giveaway winners messages, and invoice messages can't be copied. A quiz poll can be copied only if the value of the field correct_option_id is known to the bot. The method is analogous to the method forwardMessages, but the copied messages don't have a link to the original message. Album grouping is kept for copied messages. On success, an array of MessageId of the sent messages */
export const copyMessages = Rpc.make("copyMessages", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		from_chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_ids: Schema.Array(Schema.Int),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		remove_caption: Schema.optional(Schema.Boolean),
	},
	success: Objects.MessageId,
});

/** Use this method to create an additional invite link for a chat. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. The link can be revoked using the method revokeChatInviteLink */
export const createChatInviteLink = Rpc.make("createChatInviteLink", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		name: Schema.optional(Schema.String),
		expire_date: Schema.optional(Schema.Int),
		member_limit: Schema.optional(Schema.Int),
		creates_join_request: Schema.optional(Schema.Boolean),
	},
	success: Objects.ChatInviteLink,
});

/** Use this method to create a subscription invite link for a channel chat. The bot must have the can_invite_users administrator rights. The link can be edited using the method editChatSubscriptionInviteLink or revoked using the method revokeChatInviteLink */
export const createChatSubscriptionInviteLink = Rpc.make("createChatSubscriptionInviteLink", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		name: Schema.optional(Schema.String),
		subscription_period: Schema.Int,
		subscription_price: Schema.Int,
	},
	success: Objects.ChatInviteLink,
});

/** Use this method to create a topic in a forum supergroup chat or a private chat with a user. In the case of a supergroup chat the bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator right */
export const createForumTopic = Rpc.make("createForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		name: Schema.String,
		icon_color: Schema.optional(Schema.Int),
		icon_custom_emoji_id: Schema.optional(Schema.String),
	},
	success: Objects.ForumTopic,
});

/** Use this method to decline a chat join request. The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right */
export const declineChatJoinRequest = Rpc.make("declineChatJoinRequest", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Delete messages on behalf of a business account. Requires the can_delete_sent_messages business bot right to delete messages sent by the bot itself, or the can_delete_all_messages business bot right to delete any message */
export const deleteBusinessMessages = Rpc.make("deleteBusinessMessages", {
	payload: {
		business_connection_id: Schema.String,
		message_ids: Schema.Array(Schema.Int),
	},
	success: Schema.Literal(true),
});

/** Use this method to delete a chat photo. Photos can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const deleteChatPhoto = Rpc.make("deleteChatPhoto", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method to delete a group sticker set from a supergroup. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Use the field can_set_sticker_set optionally returned in getChat requests to check if the bot can use this method */
export const deleteChatStickerSet = Rpc.make("deleteChatStickerSet", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method to delete a forum topic along with all its messages in a forum supergroup chat or a private chat with a user. In the case of a supergroup chat the bot must be an administrator in the chat for this to work and must have the can_delete_messages administrator rights */
export const deleteForumTopic = Rpc.make("deleteForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to delete the list of the bot's commands for the given scope and user language. After deletion, higher level commands will be shown to affected users */
export const deleteMyCommands = Rpc.make("deleteMyCommands", {
	payload: {
		scope: Schema.optional(Objects.BotCommandScope),
		language_code: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Deletes a story previously posted by the bot on behalf of a managed business account. Requires the can_manage_stories business bot right */
export const deleteStory = Rpc.make("deleteStory", {
	payload: {
		business_connection_id: Schema.String,
		story_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to edit a non-primary invite link created by the bot. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const editChatInviteLink = Rpc.make("editChatInviteLink", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		invite_link: Schema.String,
		name: Schema.optional(Schema.String),
		expire_date: Schema.optional(Schema.Int),
		member_limit: Schema.optional(Schema.Int),
		creates_join_request: Schema.optional(Schema.Boolean),
	},
	success: Objects.ChatInviteLink,
});

/** Use this method to edit a subscription invite link created by the bot. The bot must have the can_invite_users administrator rights */
export const editChatSubscriptionInviteLink = Rpc.make("editChatSubscriptionInviteLink", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		invite_link: Schema.String,
		name: Schema.optional(Schema.String),
	},
	success: Objects.ChatInviteLink,
});

/** Use this method to edit name and icon of a topic in a forum supergroup chat or a private chat with a user. In the case of a supergroup chat the bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic */
export const editForumTopic = Rpc.make("editForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.Int,
		name: Schema.optional(Schema.String),
		icon_custom_emoji_id: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Use this method to edit the name of the 'General' topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights */
export const editGeneralForumTopic = Rpc.make("editGeneralForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		name: Schema.String,
	},
	success: Schema.Literal(true),
});

/** Edits a story previously posted by the bot on behalf of a managed business account. Requires the can_manage_stories business bot right */
export const editStory = Rpc.make("editStory", {
	payload: {
		business_connection_id: Schema.String,
		story_id: Schema.Int,
		content: Objects.InputStoryContent,
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		areas: Schema.optional(Schema.Array(Objects.StoryArea)),
	},
	success: Objects.Story,
});

/** Use this method to generate a new primary invite link for a chat; any previously generated primary link is revoked. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const exportChatInviteLink = Rpc.make("exportChatInviteLink", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.String,
});

/** Use this method to forward messages of any kind. Service messages and messages with protected content can't be forwarded. On success, the sent Message */
export const forwardMessage = Rpc.make("forwardMessage", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		from_chat_id: Schema.Union([Schema.Int, Schema.String]),
		video_start_timestamp: Schema.optional(Schema.Int),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		message_id: Schema.Int,
	},
	success: Objects.Message,
});

/** Use this method to forward multiple messages of any kind. If some of the specified messages can't be found or forwarded, they are skipped. Service messages and messages with protected content can't be forwarded. Album grouping is kept for forwarded messages. On success, an array of MessageId of the sent messages */
export const forwardMessages = Rpc.make("forwardMessages", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		from_chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_ids: Schema.Array(Schema.Int),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
	},
	success: Objects.MessageId,
});

export const getAvailableGifts = Rpc.make("getAvailableGifts", {
	success: Objects.Gifts,
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

export const getBusinessAccountGifts = Rpc.make("getBusinessAccountGifts", {
	payload: {
		business_connection_id: Schema.String,
		exclude_unsaved: Schema.optional(Schema.Boolean),
		exclude_saved: Schema.optional(Schema.Boolean),
		exclude_unlimited: Schema.optional(Schema.Boolean),
		exclude_limited_upgradable: Schema.optional(Schema.Boolean),
		exclude_limited_non_upgradable: Schema.optional(Schema.Boolean),
		exclude_unique: Schema.optional(Schema.Boolean),
		exclude_from_blockchain: Schema.optional(Schema.Boolean),
		sort_by_price: Schema.optional(Schema.Boolean),
		offset: Schema.optional(Schema.String),
		limit: Schema.optional(Schema.Int),
	},
	success: Objects.OwnedGifts,
});

export const getBusinessAccountStarBalance = Rpc.make("getBusinessAccountStarBalance", {
	payload: {
		business_connection_id: Schema.String,
	},
	success: Objects.StarAmount,
});

/** Use this method to get information about the connection of the bot with a business account */
export const getBusinessConnection = Rpc.make("getBusinessConnection", {
	payload: {
		business_connection_id: Schema.String,
	},
	success: Objects.BusinessConnection,
});

/** Use this method to get up-to-date information about the chat */
export const getChat = Rpc.make("getChat", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Objects.ChatFullInfo,
	error: Schema.Union([
		Errors.ChatIdEmptyError,
		Errors.ChatNotFoundError,
		Errors.NotFoundError,
		Errors.UnauthorizedError,
	]),
});

/** Use this method to get a list of administrators in a chat */
export const getChatAdministrators = Rpc.make("getChatAdministrators", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		return_bots: Schema.optional(Schema.Boolean),
	},
	success: Schema.Array(Objects.ChatMember),
});

export const getChatGifts = Rpc.make("getChatGifts", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		exclude_unsaved: Schema.optional(Schema.Boolean),
		exclude_saved: Schema.optional(Schema.Boolean),
		exclude_unlimited: Schema.optional(Schema.Boolean),
		exclude_limited_upgradable: Schema.optional(Schema.Boolean),
		exclude_limited_non_upgradable: Schema.optional(Schema.Boolean),
		exclude_from_blockchain: Schema.optional(Schema.Boolean),
		exclude_unique: Schema.optional(Schema.Boolean),
		sort_by_price: Schema.optional(Schema.Boolean),
		offset: Schema.optional(Schema.String),
		limit: Schema.optional(Schema.Int),
	},
	success: Objects.OwnedGifts,
});

/** Use this method to get information about a member of a chat. The method is only guaranteed to work for other users if the bot is an administrator in the chat */
export const getChatMember = Rpc.make("getChatMember", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
	},
	success: Objects.ChatMember,
});

/** Use this method to get the number of members in a chat */
export const getChatMemberCount = Rpc.make("getChatMemberCount", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Int,
});

/** Use this method to get the current value of the bot's menu button in a private chat, or the default menu button */
export const getChatMenuButton = Rpc.make("getChatMenuButton", {
	payload: {
		chat_id: Schema.optional(Schema.Int),
	},
	success: Objects.MenuButton,
});

/** Use this method to get basic information about a file and prepare it for downloading. For the moment, bots can download files of up to 20MB in size. On success, a File object */
export const getFile = Rpc.make("getFile", {
	payload: {
		file_id: Schema.String,
	},
	success: Objects.File,
	error: Schema.Union([Errors.InvalidFileIdError, Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get custom emoji stickers, which can be used as a forum topic icon by any user */
export const getForumTopicIconStickers = Rpc.make("getForumTopicIconStickers", {
	success: Schema.Array(Objects.Sticker),
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get the access settings of a managed bot */
export const getManagedBotAccessSettings = Rpc.make("getManagedBotAccessSettings", {
	payload: {
		user_id: Schema.Int,
	},
	success: Objects.BotAccessSettings,
});

/** Use this method to get the token of a managed bot */
export const getManagedBotToken = Rpc.make("getManagedBotToken", {
	payload: {
		user_id: Schema.Int,
	},
	success: Schema.String,
});

/** A simple method for testing your bot's authentication token */
export const getMe = Rpc.make("getMe", {
	success: Objects.User,
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get the current list of the bot's commands for the given scope and user language */
export const getMyCommands = Rpc.make("getMyCommands", {
	payload: {
		scope: Schema.optional(Objects.BotCommandScope),
		language_code: Schema.optional(Schema.String),
	},
	success: Schema.Array(Objects.BotCommand),
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get the current default administrator rights of the bot */
export const getMyDefaultAdministratorRights = Rpc.make("getMyDefaultAdministratorRights", {
	payload: {
		for_channels: Schema.optional(Schema.Boolean),
	},
	success: Objects.ChatAdministratorRights,
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get the current bot description for the given user language */
export const getMyDescription = Rpc.make("getMyDescription", {
	payload: {
		language_code: Schema.optional(Schema.String),
	},
	success: Objects.BotDescription,
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get the current bot name for the given user language */
export const getMyName = Rpc.make("getMyName", {
	payload: {
		language_code: Schema.optional(Schema.String),
	},
	success: Objects.BotName,
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get the current bot short description for the given user language */
export const getMyShortDescription = Rpc.make("getMyShortDescription", {
	payload: {
		language_code: Schema.optional(Schema.String),
	},
	success: Objects.BotShortDescription,
	error: Schema.Union([Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to get the list of boosts added to a chat by a user. Requires administrator rights in the chat */
export const getUserChatBoosts = Rpc.make("getUserChatBoosts", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
	},
	success: Objects.UserChatBoosts,
});

export const getUserGifts = Rpc.make("getUserGifts", {
	payload: {
		user_id: Schema.Int,
		exclude_unlimited: Schema.optional(Schema.Boolean),
		exclude_limited_upgradable: Schema.optional(Schema.Boolean),
		exclude_limited_non_upgradable: Schema.optional(Schema.Boolean),
		exclude_from_blockchain: Schema.optional(Schema.Boolean),
		exclude_unique: Schema.optional(Schema.Boolean),
		sort_by_price: Schema.optional(Schema.Boolean),
		offset: Schema.optional(Schema.String),
		limit: Schema.optional(Schema.Int),
	},
	success: Objects.OwnedGifts,
});

/** Use this method to get the last messages from the personal chat (i.e., the chat currently added to their profile) of a given user. On success, an array of Message objects */
export const getUserPersonalChatMessages = Rpc.make("getUserPersonalChatMessages", {
	payload: {
		user_id: Schema.Int,
		limit: Schema.Int,
	},
	success: Objects.Message,
});

/** Use this method to get a list of profile audios for a user */
export const getUserProfileAudios = Rpc.make("getUserProfileAudios", {
	payload: {
		user_id: Schema.Int,
		offset: Schema.optional(Schema.Int),
		limit: Schema.optional(Schema.Int),
	},
	success: Objects.UserProfileAudios,
});

/** Use this method to get a list of profile pictures for a user */
export const getUserProfilePhotos = Rpc.make("getUserProfilePhotos", {
	payload: {
		user_id: Schema.Int,
		offset: Schema.optional(Schema.Int),
		limit: Schema.optional(Schema.Int),
	},
	success: Objects.UserProfilePhotos,
});

/** Gifts a Telegram Premium subscription to the given user */
export const giftPremiumSubscription = Rpc.make("giftPremiumSubscription", {
	payload: {
		user_id: Schema.Int,
		month_count: Schema.Int,
		star_count: Schema.Int,
		text: Schema.optional(Schema.String),
		text_parse_mode: Schema.optional(Schema.String),
		text_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
	},
	success: Schema.Literal(true),
});

/** Use this method to hide the 'General' topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. The topic will be automatically closed if it was open */
export const hideGeneralForumTopic = Rpc.make("hideGeneralForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method for your bot to leave a group, supergroup or channel */
export const leaveChat = Rpc.make("leaveChat", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method to log out from the cloud Bot API server before launching the bot locally. You must log out the bot before running it locally, otherwise there is no guarantee that the bot will receive updates. After a successful call, you can immediately log in on a local server, but will not be able to log in back to the cloud Bot API server for 10 minutes */
export const logOut = Rpc.make("logOut", {
	success: Schema.Literal(true),
});

/** Use this method to add a message to the list of pinned messages in a chat. In private chats and channel direct messages chats, all non-service messages can be pinned. Conversely, the bot must be an administrator with the 'can_pin_messages' right or the 'can_edit_messages' right to pin messages in groups and channels respectively */
export const pinChatMessage = Rpc.make("pinChatMessage", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_id: Schema.Int,
		disable_notification: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Posts a story on behalf of a managed business account. Requires the can_manage_stories business bot right */
export const postStory = Rpc.make("postStory", {
	payload: {
		business_connection_id: Schema.String,
		content: Objects.InputStoryContent,
		active_period: Schema.Int,
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		areas: Schema.optional(Schema.Array(Objects.StoryArea)),
		post_to_chat_page: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
	},
	success: Objects.Story,
});

/** Use this method to promote or demote a user in a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Pass False for all boolean parameters to demote a user */
export const promoteChatMember = Rpc.make("promoteChatMember", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
		is_anonymous: Schema.optional(Schema.Boolean),
		can_manage_chat: Schema.optional(Schema.Boolean),
		can_delete_messages: Schema.optional(Schema.Boolean),
		can_manage_video_chats: Schema.optional(Schema.Boolean),
		can_restrict_members: Schema.optional(Schema.Boolean),
		can_promote_members: Schema.optional(Schema.Boolean),
		can_change_info: Schema.optional(Schema.Boolean),
		can_invite_users: Schema.optional(Schema.Boolean),
		can_post_stories: Schema.optional(Schema.Boolean),
		can_edit_stories: Schema.optional(Schema.Boolean),
		can_delete_stories: Schema.optional(Schema.Boolean),
		can_post_messages: Schema.optional(Schema.Boolean),
		can_edit_messages: Schema.optional(Schema.Boolean),
		can_pin_messages: Schema.optional(Schema.Boolean),
		can_manage_topics: Schema.optional(Schema.Boolean),
		can_manage_direct_messages: Schema.optional(Schema.Boolean),
		can_manage_tags: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Marks incoming message as read on behalf of a business account. Requires the can_read_messages business bot right */
export const readBusinessMessage = Rpc.make("readBusinessMessage", {
	payload: {
		business_connection_id: Schema.String,
		chat_id: Schema.Int,
		message_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Removes the current profile photo of a managed business account. Requires the can_edit_profile_photo business bot right */
export const removeBusinessAccountProfilePhoto = Rpc.make("removeBusinessAccountProfilePhoto", {
	payload: {
		business_connection_id: Schema.String,
		is_public: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Removes verification from a chat that is currently verified on behalf of the organization represented by the bot */
export const removeChatVerification = Rpc.make("removeChatVerification", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Removes the profile photo of the bot */
export const removeMyProfilePhoto = Rpc.make("removeMyProfilePhoto", {
	success: Schema.Literal(true),
});

/** Removes verification from a user who is currently verified on behalf of the organization represented by the bot */
export const removeUserVerification = Rpc.make("removeUserVerification", {
	payload: {
		user_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to reopen a closed topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic */
export const reopenForumTopic = Rpc.make("reopenForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to reopen a closed 'General' topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. The topic will be automatically unhidden if it was hidden */
export const reopenGeneralForumTopic = Rpc.make("reopenGeneralForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method to revoke the current token of a managed bot and generate a new one */
export const replaceManagedBotToken = Rpc.make("replaceManagedBotToken", {
	payload: {
		user_id: Schema.Int,
	},
	success: Schema.String,
});

/** Reposts a story on behalf of a business account from another business account. Both business accounts must be managed by the same bot, and the story on the source account must have been posted (or reposted) by the bot. Requires the can_manage_stories business bot right for both business accounts */
export const repostStory = Rpc.make("repostStory", {
	payload: {
		business_connection_id: Schema.String,
		from_chat_id: Schema.Int,
		from_story_id: Schema.Int,
		active_period: Schema.Int,
		post_to_chat_page: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
	},
	success: Objects.Story,
});

/** Use this method to restrict a user in a supergroup. The bot must be an administrator in the supergroup for this to work and must have the appropriate administrator rights. Pass True for all permissions to lift restrictions from a user */
export const restrictChatMember = Rpc.make("restrictChatMember", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
		permissions: Objects.ChatPermissions,
		use_independent_chat_permissions: Schema.optional(Schema.Boolean),
		until_date: Schema.optional(Schema.Int),
	},
	success: Schema.Literal(true),
});

/** Use this method to revoke an invite link created by the bot. If the primary link is revoked, a new link is automatically generated. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const revokeChatInviteLink = Rpc.make("revokeChatInviteLink", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		invite_link: Schema.String,
	},
	success: Objects.ChatInviteLink,
});

/** Stores a message that can be sent by a user of a Mini App */
export const savePreparedInlineMessage = Rpc.make("savePreparedInlineMessage", {
	payload: {
		user_id: Schema.Int,
		result: Objects.InlineQueryResult,
		allow_user_chats: Schema.optional(Schema.Boolean),
		allow_bot_chats: Schema.optional(Schema.Boolean),
		allow_group_chats: Schema.optional(Schema.Boolean),
		allow_channel_chats: Schema.optional(Schema.Boolean),
	},
	success: Objects.PreparedInlineMessage,
});

/** Stores a keyboard button that can be used by a user within a Mini App */
export const savePreparedKeyboardButton = Rpc.make("savePreparedKeyboardButton", {
	payload: {
		user_id: Schema.Int,
		button: Objects.KeyboardButton,
	},
	success: Objects.PreparedKeyboardButton,
});

/** Use this method to send animation files (GIF or H.264/MPEG-4 AVC video without sound). On success, the sent Message */
export const sendAnimation = Rpc.make("sendAnimation", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		animation: Schema.Union([Objects.InputFile, Schema.String]),
		duration: Schema.optional(Schema.Int),
		width: Schema.optional(Schema.Int),
		height: Schema.optional(Schema.Int),
		thumbnail: Schema.optional(Schema.Union([Objects.InputFile, Schema.String])),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		show_caption_above_media: Schema.optional(Schema.Boolean),
		has_spoiler: Schema.optional(Schema.Boolean),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send audio files, if you want Telegram clients to display them in the music player. Your audio must be in the .MP3 or .M4A format. On success, the sent Message */
export const sendAudio = Rpc.make("sendAudio", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		audio: Schema.Union([Objects.InputFile, Schema.String]),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		duration: Schema.optional(Schema.Int),
		performer: Schema.optional(Schema.String),
		title: Schema.optional(Schema.String),
		thumbnail: Schema.optional(Schema.Union([Objects.InputFile, Schema.String])),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method when you need to tell the user that something is happening on the bot's side. The status is set for 5 seconds or less (when a message arrives from your bot, Telegram clients clear its typing status) */
export const sendChatAction = Rpc.make("sendChatAction", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		action: Schema.String,
	},
	success: Schema.Literal(true),
});

/** Use this method to send a checklist on behalf of a connected business account. On success, the sent Message */
export const sendChecklist = Rpc.make("sendChecklist", {
	payload: {
		business_connection_id: Schema.String,
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		checklist: Objects.InputChecklist,
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(Objects.InlineKeyboardMarkup),
	},
	success: Objects.Message,
});

/** Use this method to send phone contacts. On success, the sent Message */
export const sendContact = Rpc.make("sendContact", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		phone_number: Schema.String,
		first_name: Schema.String,
		last_name: Schema.optional(Schema.String),
		vcard: Schema.optional(Schema.String),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send an animated emoji that will display a random value. On success, the sent Message */
export const sendDice = Rpc.make("sendDice", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		emoji: Schema.optional(Schema.String),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send general files. On success, the sent Message */
export const sendDocument = Rpc.make("sendDocument", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		document: Schema.Union([Objects.InputFile, Schema.String]),
		thumbnail: Schema.optional(Schema.Union([Objects.InputFile, Schema.String])),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		disable_content_type_detection: Schema.optional(Schema.Boolean),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Sends a gift to the given user or channel chat. The gift can't be converted to Telegram Stars by the receiver */
export const sendGift = Rpc.make("sendGift", {
	payload: {
		user_id: Schema.optional(Schema.Int),
		chat_id: Schema.optional(Schema.Union([Schema.Int, Schema.String])),
		gift_id: Schema.String,
		pay_for_upgrade: Schema.optional(Schema.Boolean),
		text: Schema.optional(Schema.String),
		text_parse_mode: Schema.optional(Schema.String),
		text_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
	},
	success: Schema.Literal(true),
});

/** Use this method to send live photos. On success, the sent Message */
export const sendLivePhoto = Rpc.make("sendLivePhoto", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		live_photo: Schema.Union([Objects.InputFile, Schema.String]),
		photo: Schema.Union([Objects.InputFile, Schema.String]),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		show_caption_above_media: Schema.optional(Schema.Boolean),
		has_spoiler: Schema.optional(Schema.Boolean),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send point on the map. On success, the sent Message */
export const sendLocation = Rpc.make("sendLocation", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		latitude: Schema.Number,
		longitude: Schema.Number,
		horizontal_accuracy: Schema.optional(Schema.Number),
		live_period: Schema.optional(Schema.Int),
		heading: Schema.optional(Schema.Int),
		proximity_alert_radius: Schema.optional(Schema.Int),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send a group of photos, live photos, videos, documents or audios as an album. Documents and audio files can be only grouped in an album with messages of the same type. On success, an array of Message objects that were sent */
export const sendMediaGroup = Rpc.make("sendMediaGroup", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		media: Schema.Array(
			Schema.Union([
				Objects.InputMediaAudio,
				Objects.InputMediaDocument,
				Objects.InputMediaLivePhoto,
				Objects.InputMediaPhoto,
				Objects.InputMediaVideo,
			]),
		),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
	},
	success: Objects.Message,
});

/** Use this method to send text messages. On success, the sent Message */
export const sendMessage = Rpc.make("sendMessage", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		text: Schema.String,
		parse_mode: Schema.optional(Schema.String),
		entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		link_preview_options: Schema.optional(Objects.LinkPreviewOptions),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
	error: Schema.Union([Errors.MessageTextEmptyError, Errors.NotFoundError, Errors.UnauthorizedError]),
});

/** Use this method to stream a partial message to a user while the message is being generated. Note that the streamed draft is ephemeral and acts as a temporary 30-second preview - once the output is finalized, you must call sendMessage with the complete message to persist it in the user's chat */
export const sendMessageDraft = Rpc.make("sendMessageDraft", {
	payload: {
		chat_id: Schema.Int,
		message_thread_id: Schema.optional(Schema.Int),
		draft_id: Schema.Int,
		text: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
	},
	success: Schema.Literal(true),
});

/** Use this method to send paid media. On success, the sent Message */
export const sendPaidMedia = Rpc.make("sendPaidMedia", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		star_count: Schema.Int,
		media: Schema.Array(Objects.InputPaidMedia),
		payload: Schema.optional(Schema.String),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		show_caption_above_media: Schema.optional(Schema.Boolean),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send photos. On success, the sent Message */
export const sendPhoto = Rpc.make("sendPhoto", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		photo: Schema.Union([Objects.InputFile, Schema.String]),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		show_caption_above_media: Schema.optional(Schema.Boolean),
		has_spoiler: Schema.optional(Schema.Boolean),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send a native poll. On success, the sent Message */
export const sendPoll = Rpc.make("sendPoll", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		question: Schema.String,
		question_parse_mode: Schema.optional(Schema.String),
		question_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		options: Schema.Array(Objects.InputPollOption),
		is_anonymous: Schema.optional(Schema.Boolean),
		type: Schema.optional(Schema.String),
		allows_multiple_answers: Schema.optional(Schema.Boolean),
		allows_revoting: Schema.optional(Schema.Boolean),
		shuffle_options: Schema.optional(Schema.Boolean),
		allow_adding_options: Schema.optional(Schema.Boolean),
		hide_results_until_closes: Schema.optional(Schema.Boolean),
		members_only: Schema.optional(Schema.Boolean),
		country_codes: Schema.optional(Schema.Array(Schema.String)),
		correct_option_ids: Schema.optional(Schema.Array(Schema.Int)),
		explanation: Schema.optional(Schema.String),
		explanation_parse_mode: Schema.optional(Schema.String),
		explanation_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		explanation_media: Schema.optional(Objects.InputPollMedia),
		open_period: Schema.optional(Schema.Int),
		close_date: Schema.optional(Schema.Int),
		is_closed: Schema.optional(Schema.Boolean),
		description: Schema.optional(Schema.String),
		description_parse_mode: Schema.optional(Schema.String),
		description_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		media: Schema.optional(Objects.InputPollMedia),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send information about a venue. On success, the sent Message */
export const sendVenue = Rpc.make("sendVenue", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		latitude: Schema.Number,
		longitude: Schema.Number,
		title: Schema.String,
		address: Schema.String,
		foursquare_id: Schema.optional(Schema.String),
		foursquare_type: Schema.optional(Schema.String),
		google_place_id: Schema.optional(Schema.String),
		google_place_type: Schema.optional(Schema.String),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send video files, Telegram clients support MPEG4 videos (other formats may be sent as Document). On success, the sent Message */
export const sendVideo = Rpc.make("sendVideo", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		video: Schema.Union([Objects.InputFile, Schema.String]),
		duration: Schema.optional(Schema.Int),
		width: Schema.optional(Schema.Int),
		height: Schema.optional(Schema.Int),
		thumbnail: Schema.optional(Schema.Union([Objects.InputFile, Schema.String])),
		cover: Schema.optional(Schema.Union([Objects.InputFile, Schema.String])),
		start_timestamp: Schema.optional(Schema.Int),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		show_caption_above_media: Schema.optional(Schema.Boolean),
		has_spoiler: Schema.optional(Schema.Boolean),
		supports_streaming: Schema.optional(Schema.Boolean),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** As of v.4.0, Telegram clients support rounded square MPEG4 videos of up to 1 minute long. Use this method to send video messages. On success, the sent Message */
export const sendVideoNote = Rpc.make("sendVideoNote", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		video_note: Schema.Union([Objects.InputFile, Schema.String]),
		duration: Schema.optional(Schema.Int),
		length: Schema.optional(Schema.Int),
		thumbnail: Schema.optional(Schema.Union([Objects.InputFile, Schema.String])),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Use this method to send audio files, if you want Telegram clients to display the file as a playable voice message. For this to work, your audio must be in an .OGG file encoded with OPUS, or in .MP3 format, or in .M4A format (other formats may be sent as Audio or Document). On success, the sent Message */
export const sendVoice = Rpc.make("sendVoice", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.optional(Schema.Int),
		direct_messages_topic_id: Schema.optional(Schema.Int),
		voice: Schema.Union([Objects.InputFile, Schema.String]),
		caption: Schema.optional(Schema.String),
		parse_mode: Schema.optional(Schema.String),
		caption_entities: Schema.optional(Schema.Array(Objects.MessageEntity)),
		duration: Schema.optional(Schema.Int),
		disable_notification: Schema.optional(Schema.Boolean),
		protect_content: Schema.optional(Schema.Boolean),
		allow_paid_broadcast: Schema.optional(Schema.Boolean),
		message_effect_id: Schema.optional(Schema.String),
		suggested_post_parameters: Schema.optional(Objects.SuggestedPostParameters),
		reply_parameters: Schema.optional(Objects.ReplyParameters),
		reply_markup: Schema.optional(
			Schema.Union([
				Objects.InlineKeyboardMarkup,
				Objects.ReplyKeyboardMarkup,
				Objects.ReplyKeyboardRemove,
				Objects.ForceReply,
			]),
		),
	},
	success: Objects.Message,
});

/** Changes the bio of a managed business account. Requires the can_change_bio business bot right */
export const setBusinessAccountBio = Rpc.make("setBusinessAccountBio", {
	payload: {
		business_connection_id: Schema.String,
		bio: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Changes the privacy settings pertaining to incoming gifts in a managed business account. Requires the can_change_gift_settings business bot right */
export const setBusinessAccountGiftSettings = Rpc.make("setBusinessAccountGiftSettings", {
	payload: {
		business_connection_id: Schema.String,
		show_gift_button: Schema.Boolean,
		accepted_gift_types: Objects.AcceptedGiftTypes,
	},
	success: Schema.Literal(true),
});

/** Changes the first and last name of a managed business account. Requires the can_change_name business bot right */
export const setBusinessAccountName = Rpc.make("setBusinessAccountName", {
	payload: {
		business_connection_id: Schema.String,
		first_name: Schema.String,
		last_name: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Changes the profile photo of a managed business account. Requires the can_edit_profile_photo business bot right */
export const setBusinessAccountProfilePhoto = Rpc.make("setBusinessAccountProfilePhoto", {
	payload: {
		business_connection_id: Schema.String,
		photo: Objects.InputProfilePhoto,
		is_public: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Changes the username of a managed business account. Requires the can_change_username business bot right */
export const setBusinessAccountUsername = Rpc.make("setBusinessAccountUsername", {
	payload: {
		business_connection_id: Schema.String,
		username: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Use this method to set a custom title for an administrator in a supergroup promoted by the bot */
export const setChatAdministratorCustomTitle = Rpc.make("setChatAdministratorCustomTitle", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
		custom_title: Schema.String,
	},
	success: Schema.Literal(true),
});

/** Use this method to change the description of a group, a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const setChatDescription = Rpc.make("setChatDescription", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		description: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Use this method to set a tag for a regular member in a group or a supergroup. The bot must be an administrator in the chat for this to work and must have the can_manage_tags administrator right */
export const setChatMemberTag = Rpc.make("setChatMemberTag", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
		tag: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Use this method to change the bot's menu button in a private chat, or the default menu button */
export const setChatMenuButton = Rpc.make("setChatMenuButton", {
	payload: {
		chat_id: Schema.optional(Schema.Int),
		menu_button: Schema.optional(Objects.MenuButton),
	},
	success: Schema.Literal(true),
});

/** Use this method to set default chat permissions for all members. The bot must be an administrator in the group or a supergroup for this to work and must have the can_restrict_members administrator rights */
export const setChatPermissions = Rpc.make("setChatPermissions", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		permissions: Objects.ChatPermissions,
		use_independent_chat_permissions: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Use this method to set a new profile photo for the chat. Photos can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const setChatPhoto = Rpc.make("setChatPhoto", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		photo: Objects.InputFile,
	},
	success: Schema.Literal(true),
});

/** Use this method to set a new group sticker set for a supergroup. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Use the field can_set_sticker_set optionally returned in getChat requests to check if the bot can use this method */
export const setChatStickerSet = Rpc.make("setChatStickerSet", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		sticker_set_name: Schema.String,
	},
	success: Schema.Literal(true),
});

/** Use this method to change the title of a chat. Titles can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights */
export const setChatTitle = Rpc.make("setChatTitle", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		title: Schema.String,
	},
	success: Schema.Literal(true),
});

/** Use this method to change the access settings of a managed bot */
export const setManagedBotAccessSettings = Rpc.make("setManagedBotAccessSettings", {
	payload: {
		user_id: Schema.Int,
		is_access_restricted: Schema.Boolean,
		added_user_ids: Schema.optional(Schema.Array(Schema.Int)),
	},
	success: Schema.Literal(true),
});

/** Use this method to change the chosen reactions on a message. Service messages of some types can't be reacted to. Automatically forwarded messages from a channel to its discussion group have the same available reactions as messages in the channel. Bots can't use paid reactions */
export const setMessageReaction = Rpc.make("setMessageReaction", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_id: Schema.Int,
		reaction: Schema.optional(Schema.Array(Objects.ReactionType)),
		is_big: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Use this method to change the list of the bot's commands. See this manual for more details about bot commands */
export const setMyCommands = Rpc.make("setMyCommands", {
	payload: {
		commands: Schema.Array(Objects.BotCommand),
		scope: Schema.optional(Objects.BotCommandScope),
		language_code: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Use this method to change the default administrator rights requested by the bot when it's added as an administrator to groups or channels. These rights will be suggested to users, but they are free to modify the list before adding the bot */
export const setMyDefaultAdministratorRights = Rpc.make("setMyDefaultAdministratorRights", {
	payload: {
		rights: Schema.optional(Objects.ChatAdministratorRights),
		for_channels: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Use this method to change the bot's description, which is shown in the chat with the bot if the chat is empty */
export const setMyDescription = Rpc.make("setMyDescription", {
	payload: {
		description: Schema.optional(Schema.String),
		language_code: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Use this method to change the bot's name */
export const setMyName = Rpc.make("setMyName", {
	payload: {
		name: Schema.optional(Schema.String),
		language_code: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Changes the profile photo of the bot */
export const setMyProfilePhoto = Rpc.make("setMyProfilePhoto", {
	payload: {
		photo: Objects.InputProfilePhoto,
	},
	success: Schema.Literal(true),
});

/** Use this method to change the bot's short description, which is shown on the bot's profile page and is sent together with the link when users share the bot */
export const setMyShortDescription = Rpc.make("setMyShortDescription", {
	payload: {
		short_description: Schema.optional(Schema.String),
		language_code: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Changes the emoji status for a given user that previously allowed the bot to manage their emoji status via the Mini App method requestEmojiStatusAccess */
export const setUserEmojiStatus = Rpc.make("setUserEmojiStatus", {
	payload: {
		user_id: Schema.Int,
		emoji_status_custom_emoji_id: Schema.optional(Schema.String),
		emoji_status_expiration_date: Schema.optional(Schema.Int),
	},
	success: Schema.Literal(true),
});

/** Transfers Telegram Stars from the business account balance to the bot's balance. Requires the can_transfer_stars business bot right */
export const transferBusinessAccountStars = Rpc.make("transferBusinessAccountStars", {
	payload: {
		business_connection_id: Schema.String,
		star_count: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Transfers an owned unique gift to another user. Requires the can_transfer_and_upgrade_gifts business bot right. Requires can_transfer_stars business bot right if the transfer is paid */
export const transferGift = Rpc.make("transferGift", {
	payload: {
		business_connection_id: Schema.String,
		owned_gift_id: Schema.String,
		new_owner_chat_id: Schema.Int,
		star_count: Schema.optional(Schema.Int),
	},
	success: Schema.Literal(true),
});

/** Use this method to unban a previously banned user in a supergroup or channel. The user will not return to the group or channel automatically, but will be able to join via link, etc. The bot must be an administrator for this to work. By default, this method guarantees that after the call the user is not a member of the chat, but will be able to join it. So if the user is a member of the chat they will also be removed from the chat. If you don't want this, use the parameter only_if_banned */
export const unbanChatMember = Rpc.make("unbanChatMember", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		user_id: Schema.Int,
		only_if_banned: Schema.optional(Schema.Boolean),
	},
	success: Schema.Literal(true),
});

/** Use this method to unban a previously banned channel chat in a supergroup or channel. The bot must be an administrator for this to work and must have the appropriate administrator rights */
export const unbanChatSenderChat = Rpc.make("unbanChatSenderChat", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		sender_chat_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to unhide the 'General' topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights */
export const unhideGeneralForumTopic = Rpc.make("unhideGeneralForumTopic", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method to clear the list of pinned messages in a chat. In private chats and channel direct messages chats, no additional rights are required to unpin all pinned messages. Conversely, the bot must be an administrator with the 'can_pin_messages' right or the 'can_edit_messages' right to unpin all pinned messages in groups and channels respectively */
export const unpinAllChatMessages = Rpc.make("unpinAllChatMessages", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method to clear the list of pinned messages in a forum topic in a forum supergroup chat or a private chat with a user. In the case of a supergroup chat the bot must be an administrator in the chat for this to work and must have the can_pin_messages administrator right in the supergroup */
export const unpinAllForumTopicMessages = Rpc.make("unpinAllForumTopicMessages", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_thread_id: Schema.Int,
	},
	success: Schema.Literal(true),
});

/** Use this method to clear the list of pinned messages in a General forum topic. The bot must be an administrator in the chat for this to work and must have the can_pin_messages administrator right in the supergroup */
export const unpinAllGeneralForumTopicMessages = Rpc.make("unpinAllGeneralForumTopicMessages", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
	},
	success: Schema.Literal(true),
});

/** Use this method to remove a message from the list of pinned messages in a chat. In private chats and channel direct messages chats, all messages can be unpinned. Conversely, the bot must be an administrator with the 'can_pin_messages' right or the 'can_edit_messages' right to unpin messages in groups and channels respectively */
export const unpinChatMessage = Rpc.make("unpinChatMessage", {
	payload: {
		business_connection_id: Schema.optional(Schema.String),
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		message_id: Schema.optional(Schema.Int),
	},
	success: Schema.Literal(true),
});

/** Upgrades a given regular gift to a unique gift. Requires the can_transfer_and_upgrade_gifts business bot right. Additionally requires the can_transfer_stars business bot right if the upgrade is paid */
export const upgradeGift = Rpc.make("upgradeGift", {
	payload: {
		business_connection_id: Schema.String,
		owned_gift_id: Schema.String,
		keep_original_details: Schema.optional(Schema.Boolean),
		star_count: Schema.optional(Schema.Int),
	},
	success: Schema.Literal(true),
});

/** Verifies a chat on behalf of the organization which is represented by the bot */
export const verifyChat = Rpc.make("verifyChat", {
	payload: {
		chat_id: Schema.Union([Schema.Int, Schema.String]),
		custom_description: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

/** Verifies a user on behalf of the organization which is represented by the bot */
export const verifyUser = Rpc.make("verifyUser", {
	payload: {
		user_id: Schema.Int,
		custom_description: Schema.optional(Schema.String),
	},
	success: Schema.Literal(true),
});

export const TelegramBotApi = RpcGroup.make(
	answerCallbackQuery,
	answerGuestQuery,
	answerWebAppQuery,
	approveChatJoinRequest,
	banChatMember,
	banChatSenderChat,
	close,
	closeForumTopic,
	closeGeneralForumTopic,
	convertGiftToStars,
	copyMessage,
	copyMessages,
	createChatInviteLink,
	createChatSubscriptionInviteLink,
	createForumTopic,
	declineChatJoinRequest,
	deleteBusinessMessages,
	deleteChatPhoto,
	deleteChatStickerSet,
	deleteForumTopic,
	deleteMyCommands,
	deleteStory,
	editChatInviteLink,
	editChatSubscriptionInviteLink,
	editForumTopic,
	editGeneralForumTopic,
	editStory,
	exportChatInviteLink,
	forwardMessage,
	forwardMessages,
	getAvailableGifts,
	getBusinessAccountGifts,
	getBusinessAccountStarBalance,
	getBusinessConnection,
	getChat,
	getChatAdministrators,
	getChatGifts,
	getChatMember,
	getChatMemberCount,
	getChatMenuButton,
	getFile,
	getForumTopicIconStickers,
	getManagedBotAccessSettings,
	getManagedBotToken,
	getMe,
	getMyCommands,
	getMyDefaultAdministratorRights,
	getMyDescription,
	getMyName,
	getMyShortDescription,
	getUserChatBoosts,
	getUserGifts,
	getUserPersonalChatMessages,
	getUserProfileAudios,
	getUserProfilePhotos,
	giftPremiumSubscription,
	hideGeneralForumTopic,
	leaveChat,
	logOut,
	pinChatMessage,
	postStory,
	promoteChatMember,
	readBusinessMessage,
	removeBusinessAccountProfilePhoto,
	removeChatVerification,
	removeMyProfilePhoto,
	removeUserVerification,
	reopenForumTopic,
	reopenGeneralForumTopic,
	replaceManagedBotToken,
	repostStory,
	restrictChatMember,
	revokeChatInviteLink,
	savePreparedInlineMessage,
	savePreparedKeyboardButton,
	sendAnimation,
	sendAudio,
	sendChatAction,
	sendChecklist,
	sendContact,
	sendDice,
	sendDocument,
	sendGift,
	sendLivePhoto,
	sendLocation,
	sendMediaGroup,
	sendMessage,
	sendMessageDraft,
	sendPaidMedia,
	sendPhoto,
	sendPoll,
	sendVenue,
	sendVideo,
	sendVideoNote,
	sendVoice,
	setBusinessAccountBio,
	setBusinessAccountGiftSettings,
	setBusinessAccountName,
	setBusinessAccountProfilePhoto,
	setBusinessAccountUsername,
	setChatAdministratorCustomTitle,
	setChatDescription,
	setChatMemberTag,
	setChatMenuButton,
	setChatPermissions,
	setChatPhoto,
	setChatStickerSet,
	setChatTitle,
	setManagedBotAccessSettings,
	setMessageReaction,
	setMyCommands,
	setMyDefaultAdministratorRights,
	setMyDescription,
	setMyName,
	setMyProfilePhoto,
	setMyShortDescription,
	setUserEmojiStatus,
	transferBusinessAccountStars,
	transferGift,
	unbanChatMember,
	unbanChatSenderChat,
	unhideGeneralForumTopic,
	unpinAllChatMessages,
	unpinAllForumTopicMessages,
	unpinAllGeneralForumTopicMessages,
	unpinChatMessage,
	upgradeGift,
	verifyChat,
	verifyUser,
);
