// Generated by `pnpm codegen` from data/spec. Do not edit manually.

import * as Schema from "effect/Schema";

/** A file to be uploaded to Telegram via multipart/form-data. */
export const InputFile = Schema.Uint8Array;
export type InputFile = typeof InputFile.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const BackgroundFill = Schema.Unknown;
export type BackgroundFill = typeof BackgroundFill.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const BackgroundType = Schema.Unknown;
export type BackgroundType = typeof BackgroundType.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const BotCommandScope = Schema.Unknown;
export type BotCommandScope = typeof BotCommandScope.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const CallbackGame = Schema.Unknown;
export type CallbackGame = typeof CallbackGame.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const ChatBoostSource = Schema.Unknown;
export type ChatBoostSource = typeof ChatBoostSource.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const ChatMember = Schema.Unknown;
export type ChatMember = typeof ChatMember.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const ForumTopicClosed = Schema.Unknown;
export type ForumTopicClosed = typeof ForumTopicClosed.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const ForumTopicReopened = Schema.Unknown;
export type ForumTopicReopened = typeof ForumTopicReopened.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const Game = Schema.Unknown;
export type Game = typeof Game.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const GeneralForumTopicHidden = Schema.Unknown;
export type GeneralForumTopicHidden = typeof GeneralForumTopicHidden.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const GeneralForumTopicUnhidden = Schema.Unknown;
export type GeneralForumTopicUnhidden = typeof GeneralForumTopicUnhidden.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const InlineQueryResult = Schema.Unknown;
export type InlineQueryResult = typeof InlineQueryResult.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const InputPaidMedia = Schema.Unknown;
export type InputPaidMedia = typeof InputPaidMedia.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const InputPollMedia = Schema.Unknown;
export type InputPollMedia = typeof InputPollMedia.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const InputPollOptionMedia = Schema.Unknown;
export type InputPollOptionMedia = typeof InputPollOptionMedia.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const InputProfilePhoto = Schema.Unknown;
export type InputProfilePhoto = typeof InputProfilePhoto.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const InputStoryContent = Schema.Unknown;
export type InputStoryContent = typeof InputStoryContent.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const Invoice = Schema.Unknown;
export type Invoice = typeof Invoice.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const MaybeInaccessibleMessage = Schema.Unknown;
export type MaybeInaccessibleMessage = typeof MaybeInaccessibleMessage.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const MenuButton = Schema.Unknown;
export type MenuButton = typeof MenuButton.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const MessageOrigin = Schema.Unknown;
export type MessageOrigin = typeof MessageOrigin.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const OwnedGift = Schema.Unknown;
export type OwnedGift = typeof OwnedGift.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const PaidMedia = Schema.Unknown;
export type PaidMedia = typeof PaidMedia.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const PassportData = Schema.Unknown;
export type PassportData = typeof PassportData.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const ReactionType = Schema.Unknown;
export type ReactionType = typeof ReactionType.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const RefundedPayment = Schema.Unknown;
export type RefundedPayment = typeof RefundedPayment.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const Sticker = Schema.Unknown;
export type Sticker = typeof Sticker.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const StoryAreaType = Schema.Unknown;
export type StoryAreaType = typeof StoryAreaType.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const SuccessfulPayment = Schema.Unknown;
export type SuccessfulPayment = typeof SuccessfulPayment.Type;

// TODO: union/polymorphic type not yet generated from the spec.
export const VideoChatStarted = Schema.Unknown;
export type VideoChatStarted = typeof VideoChatStarted.Type;

/** This object describes the types of gifts that can be gifted to a user or a chat. */
export const AcceptedGiftTypes = Schema.Struct({
	unlimited_gifts: Schema.Boolean,
	limited_gifts: Schema.Boolean,
	unique_gifts: Schema.Boolean,
	premium_subscription: Schema.Boolean,
	gifts_from_channels: Schema.Boolean,
});
export type AcceptedGiftTypes = typeof AcceptedGiftTypes.Type;

/** This object represents one size of a photo or a file / sticker thumbnail. */
export const PhotoSize = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	width: Schema.Int,
	height: Schema.Int,
	file_size: Schema.optional(Schema.Int),
});
export type PhotoSize = typeof PhotoSize.Type;

/** This object represents an animation file (GIF or H.264/MPEG-4 AVC video without sound). */
export const Animation = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	width: Schema.Int,
	height: Schema.Int,
	duration: Schema.Int,
	thumbnail: Schema.optional(PhotoSize),
	file_name: Schema.optional(Schema.String),
	mime_type: Schema.optional(Schema.String),
	file_size: Schema.optional(Schema.Int),
});
export type Animation = typeof Animation.Type;

/** This object represents an audio file to be treated as music by the Telegram clients. */
export const Audio = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	duration: Schema.Int,
	performer: Schema.optional(Schema.String),
	title: Schema.optional(Schema.String),
	file_name: Schema.optional(Schema.String),
	mime_type: Schema.optional(Schema.String),
	file_size: Schema.optional(Schema.Int),
	thumbnail: Schema.optional(PhotoSize),
});
export type Audio = typeof Audio.Type;

/** The background is a freeform gradient that rotates after every message in the chat. */
export const BackgroundFillFreeformGradient = Schema.Struct({
	type: Schema.String,
	colors: Schema.Array(Schema.Int),
});
export type BackgroundFillFreeformGradient = typeof BackgroundFillFreeformGradient.Type;

/** The background is a gradient fill. */
export const BackgroundFillGradient = Schema.Struct({
	type: Schema.String,
	top_color: Schema.Int,
	bottom_color: Schema.Int,
	rotation_angle: Schema.Int,
});
export type BackgroundFillGradient = typeof BackgroundFillGradient.Type;

/** The background is filled using the selected color. */
export const BackgroundFillSolid = Schema.Struct({
	type: Schema.String,
	color: Schema.Int,
});
export type BackgroundFillSolid = typeof BackgroundFillSolid.Type;

/** The background is taken directly from a built-in chat theme. */
export const BackgroundTypeChatTheme = Schema.Struct({
	type: Schema.String,
	theme_name: Schema.String,
});
export type BackgroundTypeChatTheme = typeof BackgroundTypeChatTheme.Type;

/** The background is automatically filled based on the selected colors. */
export const BackgroundTypeFill = Schema.Struct({
	type: Schema.String,
	fill: BackgroundFill,
	dark_theme_dimming: Schema.Int,
});
export type BackgroundTypeFill = typeof BackgroundTypeFill.Type;

/** This object represents a general file (as opposed to photos, voice messages and audio files). */
export const Document = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	thumbnail: Schema.optional(PhotoSize),
	file_name: Schema.optional(Schema.String),
	mime_type: Schema.optional(Schema.String),
	file_size: Schema.optional(Schema.Int),
});
export type Document = typeof Document.Type;

/** The background is a .PNG or .TGV (gzipped subset of SVG with MIME type “application/x-tgwallpattern”) pattern to be combined with the background fill chosen by the user. */
export const BackgroundTypePattern = Schema.Struct({
	type: Schema.String,
	document: Document,
	fill: BackgroundFill,
	intensity: Schema.Int,
	is_inverted: Schema.optional(Schema.Literal(true)),
	is_moving: Schema.optional(Schema.Literal(true)),
});
export type BackgroundTypePattern = typeof BackgroundTypePattern.Type;

/** The background is a wallpaper in the JPEG format. */
export const BackgroundTypeWallpaper = Schema.Struct({
	type: Schema.String,
	document: Document,
	dark_theme_dimming: Schema.Int,
	is_blurred: Schema.optional(Schema.Literal(true)),
	is_moving: Schema.optional(Schema.Literal(true)),
});
export type BackgroundTypeWallpaper = typeof BackgroundTypeWallpaper.Type;

/** Describes the birthdate of a user. */
export const Birthdate = Schema.Struct({
	day: Schema.Int,
	month: Schema.Int,
	year: Schema.optional(Schema.Int),
});
export type Birthdate = typeof Birthdate.Type;

/** This object represents a Telegram user or bot. */
export const User = Schema.Struct({
	id: Schema.Int,
	is_bot: Schema.Boolean,
	first_name: Schema.String,
	last_name: Schema.optional(Schema.String),
	username: Schema.optional(Schema.String),
	language_code: Schema.optional(Schema.String),
	is_premium: Schema.optional(Schema.Literal(true)),
	added_to_attachment_menu: Schema.optional(Schema.Literal(true)),
	can_join_groups: Schema.optional(Schema.Boolean),
	can_read_all_group_messages: Schema.optional(Schema.Boolean),
	supports_guest_queries: Schema.optional(Schema.Boolean),
	supports_inline_queries: Schema.optional(Schema.Boolean),
	can_connect_to_business: Schema.optional(Schema.Boolean),
	has_main_web_app: Schema.optional(Schema.Boolean),
	has_topics_enabled: Schema.optional(Schema.Boolean),
	allows_users_to_create_topics: Schema.optional(Schema.Boolean),
	can_manage_bots: Schema.optional(Schema.Boolean),
});
export type User = typeof User.Type;

/** This object describes the access settings of a bot. */
export const BotAccessSettings = Schema.Struct({
	is_access_restricted: Schema.Boolean,
	added_users: Schema.optional(Schema.Array(User)),
});
export type BotAccessSettings = typeof BotAccessSettings.Type;

/** This object represents a bot command. */
export const BotCommand = Schema.Struct({
	command: Schema.String,
	description: Schema.String,
});
export type BotCommand = typeof BotCommand.Type;

/** Represents the scope of bot commands, covering all group and supergroup chat administrators. */
export const BotCommandScopeAllChatAdministrators = Schema.Struct({
	type: Schema.String,
});
export type BotCommandScopeAllChatAdministrators = typeof BotCommandScopeAllChatAdministrators.Type;

/** Represents the scope of bot commands, covering all group and supergroup chats. */
export const BotCommandScopeAllGroupChats = Schema.Struct({
	type: Schema.String,
});
export type BotCommandScopeAllGroupChats = typeof BotCommandScopeAllGroupChats.Type;

/** Represents the scope of bot commands, covering all private chats. */
export const BotCommandScopeAllPrivateChats = Schema.Struct({
	type: Schema.String,
});
export type BotCommandScopeAllPrivateChats = typeof BotCommandScopeAllPrivateChats.Type;

/** Represents the scope of bot commands, covering a specific chat. */
export const BotCommandScopeChat = Schema.Struct({
	type: Schema.String,
	chat_id: Schema.Union([Schema.Int, Schema.String]),
});
export type BotCommandScopeChat = typeof BotCommandScopeChat.Type;

/** Represents the scope of bot commands, covering all administrators of a specific group or supergroup chat. */
export const BotCommandScopeChatAdministrators = Schema.Struct({
	type: Schema.String,
	chat_id: Schema.Union([Schema.Int, Schema.String]),
});
export type BotCommandScopeChatAdministrators = typeof BotCommandScopeChatAdministrators.Type;

/** Represents the scope of bot commands, covering a specific member of a group or supergroup chat. */
export const BotCommandScopeChatMember = Schema.Struct({
	type: Schema.String,
	chat_id: Schema.Union([Schema.Int, Schema.String]),
	user_id: Schema.Int,
});
export type BotCommandScopeChatMember = typeof BotCommandScopeChatMember.Type;

/** Represents the default scope of bot commands. Default commands are used if no commands with a narrower scope are specified for the user. */
export const BotCommandScopeDefault = Schema.Struct({
	type: Schema.String,
});
export type BotCommandScopeDefault = typeof BotCommandScopeDefault.Type;

/** This object represents the bot's description. */
export const BotDescription = Schema.Struct({
	description: Schema.String,
});
export type BotDescription = typeof BotDescription.Type;

/** This object represents the bot's name. */
export const BotName = Schema.Struct({
	name: Schema.String,
});
export type BotName = typeof BotName.Type;

/** This object represents the bot's short description. */
export const BotShortDescription = Schema.Struct({
	short_description: Schema.String,
});
export type BotShortDescription = typeof BotShortDescription.Type;

/** Represents the rights of a business bot. */
export const BusinessBotRights = Schema.Struct({
	can_reply: Schema.optional(Schema.Literal(true)),
	can_read_messages: Schema.optional(Schema.Literal(true)),
	can_delete_sent_messages: Schema.optional(Schema.Literal(true)),
	can_delete_all_messages: Schema.optional(Schema.Literal(true)),
	can_edit_name: Schema.optional(Schema.Literal(true)),
	can_edit_bio: Schema.optional(Schema.Literal(true)),
	can_edit_profile_photo: Schema.optional(Schema.Literal(true)),
	can_edit_username: Schema.optional(Schema.Literal(true)),
	can_change_gift_settings: Schema.optional(Schema.Literal(true)),
	can_view_gifts_and_stars: Schema.optional(Schema.Literal(true)),
	can_convert_gifts_to_stars: Schema.optional(Schema.Literal(true)),
	can_transfer_and_upgrade_gifts: Schema.optional(Schema.Literal(true)),
	can_transfer_stars: Schema.optional(Schema.Literal(true)),
	can_manage_stories: Schema.optional(Schema.Literal(true)),
});
export type BusinessBotRights = typeof BusinessBotRights.Type;

/** Describes the connection of the bot with a business account. */
export const BusinessConnection = Schema.Struct({
	id: Schema.String,
	user: User,
	user_chat_id: Schema.Int,
	date: Schema.Int,
	rights: Schema.optional(BusinessBotRights),
	is_enabled: Schema.Boolean,
});
export type BusinessConnection = typeof BusinessConnection.Type;

/** Contains information about the start page settings of a Telegram Business account. */
export const BusinessIntro = Schema.Struct({
	title: Schema.optional(Schema.String),
	message: Schema.optional(Schema.String),
	sticker: Schema.optional(Sticker),
});
export type BusinessIntro = typeof BusinessIntro.Type;

/** This object represents a point on the map. */
export const Location = Schema.Struct({
	latitude: Schema.Number,
	longitude: Schema.Number,
	horizontal_accuracy: Schema.optional(Schema.Number),
	live_period: Schema.optional(Schema.Int),
	heading: Schema.optional(Schema.Int),
	proximity_alert_radius: Schema.optional(Schema.Int),
});
export type Location = typeof Location.Type;

/** Contains information about the location of a Telegram Business account. */
export const BusinessLocation = Schema.Struct({
	address: Schema.String,
	location: Schema.optional(Location),
});
export type BusinessLocation = typeof BusinessLocation.Type;

/** This object represents a chat. */
export const Chat = Schema.Struct({
	id: Schema.Int,
	type: Schema.String,
	title: Schema.optional(Schema.String),
	username: Schema.optional(Schema.String),
	first_name: Schema.optional(Schema.String),
	last_name: Schema.optional(Schema.String),
	is_forum: Schema.optional(Schema.Literal(true)),
	is_direct_messages: Schema.optional(Schema.Literal(true)),
});
export type Chat = typeof Chat.Type;

/** This object is received when messages are deleted from a connected business account. */
export const BusinessMessagesDeleted = Schema.Struct({
	business_connection_id: Schema.String,
	chat: Chat,
	message_ids: Schema.Array(Schema.Int),
});
export type BusinessMessagesDeleted = typeof BusinessMessagesDeleted.Type;

/** Describes an interval of time during which a business is open. */
export const BusinessOpeningHoursInterval = Schema.Struct({
	opening_minute: Schema.Int,
	closing_minute: Schema.Int,
});
export type BusinessOpeningHoursInterval = typeof BusinessOpeningHoursInterval.Type;

/** Describes the opening hours of a business. */
export const BusinessOpeningHours = Schema.Struct({
	time_zone_name: Schema.String,
	opening_hours: Schema.Array(BusinessOpeningHoursInterval),
});
export type BusinessOpeningHours = typeof BusinessOpeningHours.Type;

/** This object represents an incoming callback query from a callback button in an inline keyboard. If the button that originated the query was attached to a message sent by the bot, the field message will be present. If the button was attached to a message sent via the bot (in inline mode), the field inline_message_id will be present. Exactly one of the fields data or game_short_name will be present. */
export const CallbackQuery = Schema.Struct({
	id: Schema.String,
	from: User,
	message: Schema.optional(MaybeInaccessibleMessage),
	inline_message_id: Schema.optional(Schema.String),
	chat_instance: Schema.String,
	data: Schema.optional(Schema.String),
	game_short_name: Schema.optional(Schema.String),
});
export type CallbackQuery = typeof CallbackQuery.Type;

/** Represents the rights of an administrator in a chat. */
export const ChatAdministratorRights = Schema.Struct({
	is_anonymous: Schema.Boolean,
	can_manage_chat: Schema.Boolean,
	can_delete_messages: Schema.Boolean,
	can_manage_video_chats: Schema.Boolean,
	can_restrict_members: Schema.Boolean,
	can_promote_members: Schema.Boolean,
	can_change_info: Schema.Boolean,
	can_invite_users: Schema.Boolean,
	can_post_stories: Schema.Boolean,
	can_edit_stories: Schema.Boolean,
	can_delete_stories: Schema.Boolean,
	can_post_messages: Schema.optional(Schema.Boolean),
	can_edit_messages: Schema.optional(Schema.Boolean),
	can_pin_messages: Schema.optional(Schema.Boolean),
	can_manage_topics: Schema.optional(Schema.Boolean),
	can_manage_direct_messages: Schema.optional(Schema.Boolean),
	can_manage_tags: Schema.optional(Schema.Boolean),
});
export type ChatAdministratorRights = typeof ChatAdministratorRights.Type;

/** This object represents a chat background. */
export const ChatBackground = Schema.Struct({
	type: BackgroundType,
});
export type ChatBackground = typeof ChatBackground.Type;

/** This object contains information about a chat boost. */
export const ChatBoost = Schema.Struct({
	boost_id: Schema.String,
	add_date: Schema.Int,
	expiration_date: Schema.Int,
	source: ChatBoostSource,
});
export type ChatBoost = typeof ChatBoost.Type;

/** This object represents a service message about a user boosting a chat. */
export const ChatBoostAdded = Schema.Struct({
	boost_count: Schema.Int,
});
export type ChatBoostAdded = typeof ChatBoostAdded.Type;

/** This object represents a boost removed from a chat. */
export const ChatBoostRemoved = Schema.Struct({
	chat: Chat,
	boost_id: Schema.String,
	remove_date: Schema.Int,
	source: ChatBoostSource,
});
export type ChatBoostRemoved = typeof ChatBoostRemoved.Type;

/** The boost was obtained by the creation of Telegram Premium gift codes to boost a chat. Each such code boosts the chat 4 times for the duration of the corresponding Telegram Premium subscription. */
export const ChatBoostSourceGiftCode = Schema.Struct({
	source: Schema.String,
	user: User,
});
export type ChatBoostSourceGiftCode = typeof ChatBoostSourceGiftCode.Type;

/** The boost was obtained by the creation of a Telegram Premium or a Telegram Star giveaway. This boosts the chat 4 times for the duration of the corresponding Telegram Premium subscription for Telegram Premium giveaways and prize_star_count / 500 times for one year for Telegram Star giveaways. */
export const ChatBoostSourceGiveaway = Schema.Struct({
	source: Schema.String,
	giveaway_message_id: Schema.Int,
	user: Schema.optional(User),
	prize_star_count: Schema.optional(Schema.Int),
	is_unclaimed: Schema.optional(Schema.Literal(true)),
});
export type ChatBoostSourceGiveaway = typeof ChatBoostSourceGiveaway.Type;

/** The boost was obtained by subscribing to Telegram Premium or by gifting a Telegram Premium subscription to another user. */
export const ChatBoostSourcePremium = Schema.Struct({
	source: Schema.String,
	user: User,
});
export type ChatBoostSourcePremium = typeof ChatBoostSourcePremium.Type;

/** This object represents a boost added to a chat or changed. */
export const ChatBoostUpdated = Schema.Struct({
	chat: Chat,
	boost: ChatBoost,
});
export type ChatBoostUpdated = typeof ChatBoostUpdated.Type;

/** Represents a location to which a chat is connected. */
export const ChatLocation = Schema.Struct({
	location: Location,
	address: Schema.String,
});
export type ChatLocation = typeof ChatLocation.Type;

/** Describes actions that a non-administrator user is allowed to take in a chat. */
export const ChatPermissions = Schema.Struct({
	can_send_messages: Schema.optional(Schema.Boolean),
	can_send_audios: Schema.optional(Schema.Boolean),
	can_send_documents: Schema.optional(Schema.Boolean),
	can_send_photos: Schema.optional(Schema.Boolean),
	can_send_videos: Schema.optional(Schema.Boolean),
	can_send_video_notes: Schema.optional(Schema.Boolean),
	can_send_voice_notes: Schema.optional(Schema.Boolean),
	can_send_polls: Schema.optional(Schema.Boolean),
	can_send_other_messages: Schema.optional(Schema.Boolean),
	can_add_web_page_previews: Schema.optional(Schema.Boolean),
	can_react_to_messages: Schema.optional(Schema.Boolean),
	can_edit_tag: Schema.optional(Schema.Boolean),
	can_change_info: Schema.optional(Schema.Boolean),
	can_invite_users: Schema.optional(Schema.Boolean),
	can_pin_messages: Schema.optional(Schema.Boolean),
	can_manage_topics: Schema.optional(Schema.Boolean),
});
export type ChatPermissions = typeof ChatPermissions.Type;

/** This object represents a chat photo. */
export const ChatPhoto = Schema.Struct({
	small_file_id: Schema.String,
	small_file_unique_id: Schema.String,
	big_file_id: Schema.String,
	big_file_unique_id: Schema.String,
});
export type ChatPhoto = typeof ChatPhoto.Type;

/** Describes a service message about an ownership change in the chat. */
export const ChatOwnerChanged = Schema.Struct({
	new_owner: User,
});
export type ChatOwnerChanged = typeof ChatOwnerChanged.Type;

/** Describes a service message about the chat owner leaving the chat. */
export const ChatOwnerLeft = Schema.Struct({
	new_owner: Schema.optional(User),
});
export type ChatOwnerLeft = typeof ChatOwnerLeft.Type;

/** This object contains information about a chat that was shared with the bot using a KeyboardButtonRequestChat button. */
export const ChatShared = Schema.Struct({
	request_id: Schema.Int,
	chat_id: Schema.Int,
	title: Schema.optional(Schema.String),
	username: Schema.optional(Schema.String),
	photo: Schema.optional(Schema.Array(PhotoSize)),
});
export type ChatShared = typeof ChatShared.Type;

/** This object represents one special entity in a text message. For example, hashtags, usernames, URLs, etc. */
export const MessageEntity = Schema.Struct({
	type: Schema.String,
	offset: Schema.Int,
	length: Schema.Int,
	url: Schema.optional(Schema.String),
	user: Schema.optional(User),
	language: Schema.optional(Schema.String),
	custom_emoji_id: Schema.optional(Schema.String),
	unix_time: Schema.optional(Schema.Int),
	date_time_format: Schema.optional(Schema.String),
});
export type MessageEntity = typeof MessageEntity.Type;

/** Describes a task in a checklist. */
export const ChecklistTask = Schema.Struct({
	id: Schema.Int,
	text: Schema.String,
	text_entities: Schema.optional(Schema.Array(MessageEntity)),
	completed_by_user: Schema.optional(User),
	completed_by_chat: Schema.optional(Chat),
	completion_date: Schema.optional(Schema.Int),
});
export type ChecklistTask = typeof ChecklistTask.Type;

/** Describes a checklist. */
export const Checklist = Schema.Struct({
	title: Schema.String,
	title_entities: Schema.optional(Schema.Array(MessageEntity)),
	tasks: Schema.Array(ChecklistTask),
	others_can_add_tasks: Schema.optional(Schema.Literal(true)),
	others_can_mark_tasks_as_done: Schema.optional(Schema.Literal(true)),
});
export type Checklist = typeof Checklist.Type;

/** This object represents a phone contact. */
export const Contact = Schema.Struct({
	phone_number: Schema.String,
	first_name: Schema.String,
	last_name: Schema.optional(Schema.String),
	user_id: Schema.optional(Schema.Int),
	vcard: Schema.optional(Schema.String),
});
export type Contact = typeof Contact.Type;

/** This object represents an animated emoji that displays a random value. */
export const Dice = Schema.Struct({
	emoji: Schema.String,
	value: Schema.Int,
});
export type Dice = typeof Dice.Type;

/** Describes a service message about a change in the price of direct messages sent to a channel chat. */
export const DirectMessagePriceChanged = Schema.Struct({
	are_direct_messages_enabled: Schema.Boolean,
	direct_message_star_count: Schema.optional(Schema.Int),
});
export type DirectMessagePriceChanged = typeof DirectMessagePriceChanged.Type;

/** Describes a topic of a direct messages chat. */
export const DirectMessagesTopic = Schema.Struct({
	topic_id: Schema.Int,
	user: Schema.optional(User),
});
export type DirectMessagesTopic = typeof DirectMessagesTopic.Type;

/** This object represents a message about a scheduled giveaway. */
export const Giveaway = Schema.Struct({
	chats: Schema.Array(Chat),
	winners_selection_date: Schema.Int,
	winner_count: Schema.Int,
	only_new_members: Schema.optional(Schema.Literal(true)),
	has_public_winners: Schema.optional(Schema.Literal(true)),
	prize_description: Schema.optional(Schema.String),
	country_codes: Schema.optional(Schema.Array(Schema.String)),
	prize_star_count: Schema.optional(Schema.Int),
	premium_subscription_month_count: Schema.optional(Schema.Int),
});
export type Giveaway = typeof Giveaway.Type;

/** This object represents a message about the completion of a giveaway with public winners. */
export const GiveawayWinners = Schema.Struct({
	chat: Chat,
	giveaway_message_id: Schema.Int,
	winners_selection_date: Schema.Int,
	winner_count: Schema.Int,
	winners: Schema.Array(User),
	additional_chat_count: Schema.optional(Schema.Int),
	prize_star_count: Schema.optional(Schema.Int),
	premium_subscription_month_count: Schema.optional(Schema.Int),
	unclaimed_prize_count: Schema.optional(Schema.Int),
	only_new_members: Schema.optional(Schema.Literal(true)),
	was_refunded: Schema.optional(Schema.Literal(true)),
	prize_description: Schema.optional(Schema.String),
});
export type GiveawayWinners = typeof GiveawayWinners.Type;

/** Describes the options used for link preview generation. */
export const LinkPreviewOptions = Schema.Struct({
	is_disabled: Schema.optional(Schema.Boolean),
	url: Schema.optional(Schema.String),
	prefer_small_media: Schema.optional(Schema.Boolean),
	prefer_large_media: Schema.optional(Schema.Boolean),
	show_above_text: Schema.optional(Schema.Boolean),
});
export type LinkPreviewOptions = typeof LinkPreviewOptions.Type;

/** This object represents a live photo. */
export const LivePhoto = Schema.Struct({
	photo: Schema.optional(Schema.Array(PhotoSize)),
	file_id: Schema.String,
	file_unique_id: Schema.String,
	width: Schema.Int,
	height: Schema.Int,
	duration: Schema.Int,
	mime_type: Schema.optional(Schema.String),
	file_size: Schema.optional(Schema.Int),
});
export type LivePhoto = typeof LivePhoto.Type;

/** Describes the paid media added to a message. */
export const PaidMediaInfo = Schema.Struct({
	star_count: Schema.Int,
	paid_media: Schema.Array(PaidMedia),
});
export type PaidMediaInfo = typeof PaidMediaInfo.Type;

/** This object represents a venue. */
export const Venue = Schema.Struct({
	location: Location,
	title: Schema.String,
	address: Schema.String,
	foursquare_id: Schema.optional(Schema.String),
	foursquare_type: Schema.optional(Schema.String),
	google_place_id: Schema.optional(Schema.String),
	google_place_type: Schema.optional(Schema.String),
});
export type Venue = typeof Venue.Type;

/** This object represents a video file of a specific quality. */
export const VideoQuality = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	width: Schema.Int,
	height: Schema.Int,
	codec: Schema.String,
	file_size: Schema.optional(Schema.Int),
});
export type VideoQuality = typeof VideoQuality.Type;

/** This object represents a video file. */
export const Video = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	width: Schema.Int,
	height: Schema.Int,
	duration: Schema.Int,
	thumbnail: Schema.optional(PhotoSize),
	cover: Schema.optional(Schema.Array(PhotoSize)),
	start_timestamp: Schema.optional(Schema.Int),
	qualities: Schema.optional(Schema.Array(VideoQuality)),
	file_name: Schema.optional(Schema.String),
	mime_type: Schema.optional(Schema.String),
	file_size: Schema.optional(Schema.Int),
});
export type Video = typeof Video.Type;

/** At most one of the optional fields can be present in any given object. */
export const PollMedia = Schema.Struct({
	animation: Schema.optional(Animation),
	audio: Schema.optional(Audio),
	document: Schema.optional(Document),
	live_photo: Schema.optional(LivePhoto),
	location: Schema.optional(Location),
	photo: Schema.optional(Schema.Array(PhotoSize)),
	sticker: Schema.optional(Sticker),
	venue: Schema.optional(Venue),
	video: Schema.optional(Video),
});
export type PollMedia = typeof PollMedia.Type;

/** This object contains information about one answer option in a poll. */
export const PollOption = Schema.Struct({
	persistent_id: Schema.String,
	text: Schema.String,
	text_entities: Schema.optional(Schema.Array(MessageEntity)),
	media: Schema.optional(PollMedia),
	voter_count: Schema.Int,
	added_by_user: Schema.optional(User),
	added_by_chat: Schema.optional(Chat),
	addition_date: Schema.optional(Schema.Int),
});
export type PollOption = typeof PollOption.Type;

/** This object contains information about a poll. */
export const Poll = Schema.Struct({
	id: Schema.String,
	question: Schema.String,
	question_entities: Schema.optional(Schema.Array(MessageEntity)),
	options: Schema.Array(PollOption),
	total_voter_count: Schema.Int,
	is_closed: Schema.Boolean,
	is_anonymous: Schema.Boolean,
	type: Schema.String,
	allows_multiple_answers: Schema.Boolean,
	allows_revoting: Schema.Boolean,
	members_only: Schema.Boolean,
	country_codes: Schema.optional(Schema.Array(Schema.String)),
	correct_option_ids: Schema.optional(Schema.Array(Schema.Int)),
	explanation: Schema.optional(Schema.String),
	explanation_entities: Schema.optional(Schema.Array(MessageEntity)),
	explanation_media: Schema.optional(PollMedia),
	open_period: Schema.optional(Schema.Int),
	close_date: Schema.optional(Schema.Int),
	description: Schema.optional(Schema.String),
	description_entities: Schema.optional(Schema.Array(MessageEntity)),
	media: Schema.optional(PollMedia),
});
export type Poll = typeof Poll.Type;

/** This object represents a story. */
export const Story = Schema.Struct({
	chat: Chat,
	id: Schema.Int,
});
export type Story = typeof Story.Type;

/** This object represents a video message (available in Telegram apps as of v.4.0). */
export const VideoNote = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	length: Schema.Int,
	duration: Schema.Int,
	thumbnail: Schema.optional(PhotoSize),
	file_size: Schema.optional(Schema.Int),
});
export type VideoNote = typeof VideoNote.Type;

/** This object represents a voice note. */
export const Voice = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	duration: Schema.Int,
	mime_type: Schema.optional(Schema.String),
	file_size: Schema.optional(Schema.Int),
});
export type Voice = typeof Voice.Type;

/** This object contains information about a message that is being replied to, which may come from another chat or forum topic. */
export const ExternalReplyInfo = Schema.Struct({
	origin: MessageOrigin,
	chat: Schema.optional(Chat),
	message_id: Schema.optional(Schema.Int),
	link_preview_options: Schema.optional(LinkPreviewOptions),
	animation: Schema.optional(Animation),
	audio: Schema.optional(Audio),
	document: Schema.optional(Document),
	live_photo: Schema.optional(LivePhoto),
	paid_media: Schema.optional(PaidMediaInfo),
	photo: Schema.optional(Schema.Array(PhotoSize)),
	sticker: Schema.optional(Sticker),
	story: Schema.optional(Story),
	video: Schema.optional(Video),
	video_note: Schema.optional(VideoNote),
	voice: Schema.optional(Voice),
	has_media_spoiler: Schema.optional(Schema.Literal(true)),
	checklist: Schema.optional(Checklist),
	contact: Schema.optional(Contact),
	dice: Schema.optional(Dice),
	game: Schema.optional(Game),
	giveaway: Schema.optional(Giveaway),
	giveaway_winners: Schema.optional(GiveawayWinners),
	invoice: Schema.optional(Invoice),
	location: Schema.optional(Location),
	poll: Schema.optional(Poll),
	venue: Schema.optional(Venue),
});
export type ExternalReplyInfo = typeof ExternalReplyInfo.Type;

/** This object represents a service message about a new forum topic created in the chat. */
export const ForumTopicCreated = Schema.Struct({
	name: Schema.String,
	icon_color: Schema.Int,
	icon_custom_emoji_id: Schema.optional(Schema.String),
	is_name_implicit: Schema.optional(Schema.Literal(true)),
});
export type ForumTopicCreated = typeof ForumTopicCreated.Type;

/** This object represents a service message about an edited forum topic. */
export const ForumTopicEdited = Schema.Struct({
	name: Schema.optional(Schema.String),
	icon_custom_emoji_id: Schema.optional(Schema.String),
});
export type ForumTopicEdited = typeof ForumTopicEdited.Type;

/** This object describes the background of a gift. */
export const GiftBackground = Schema.Struct({
	center_color: Schema.Int,
	edge_color: Schema.Int,
	text_color: Schema.Int,
});
export type GiftBackground = typeof GiftBackground.Type;

/** This object represents a gift that can be sent by the bot. */
export const Gift = Schema.Struct({
	id: Schema.String,
	sticker: Sticker,
	star_count: Schema.Int,
	upgrade_star_count: Schema.optional(Schema.Int),
	is_premium: Schema.optional(Schema.Literal(true)),
	has_colors: Schema.optional(Schema.Literal(true)),
	total_count: Schema.optional(Schema.Int),
	remaining_count: Schema.optional(Schema.Int),
	personal_total_count: Schema.optional(Schema.Int),
	personal_remaining_count: Schema.optional(Schema.Int),
	background: Schema.optional(GiftBackground),
	unique_gift_variant_count: Schema.optional(Schema.Int),
	publisher_chat: Schema.optional(Chat),
});
export type Gift = typeof Gift.Type;

/** Describes a service message about a regular gift that was sent or received. */
export const GiftInfo = Schema.Struct({
	gift: Gift,
	owned_gift_id: Schema.optional(Schema.String),
	convert_star_count: Schema.optional(Schema.Int),
	prepaid_upgrade_star_count: Schema.optional(Schema.Int),
	is_upgrade_separate: Schema.optional(Schema.Literal(true)),
	can_be_upgraded: Schema.optional(Schema.Literal(true)),
	text: Schema.optional(Schema.String),
	entities: Schema.optional(Schema.Array(MessageEntity)),
	is_private: Schema.optional(Schema.Literal(true)),
	unique_gift_number: Schema.optional(Schema.Int),
});
export type GiftInfo = typeof GiftInfo.Type;

/** This object represents a service message about the creation of a scheduled giveaway. */
export const GiveawayCreated = Schema.Struct({
	prize_star_count: Schema.optional(Schema.Int),
});
export type GiveawayCreated = typeof GiveawayCreated.Type;

/** This object represents an inline keyboard button that copies specified text to the clipboard. */
export const CopyTextButton = Schema.Struct({
	text: Schema.String,
});
export type CopyTextButton = typeof CopyTextButton.Type;

/** This object represents a parameter of the inline keyboard button used to automatically authorize a user. Serves as a great replacement for the Telegram Login Widget when the user is coming from Telegram. All the user needs to do is tap/click a button and confirm that they want to log in: */
export const LoginUrl = Schema.Struct({
	url: Schema.String,
	forward_text: Schema.optional(Schema.String),
	bot_username: Schema.optional(Schema.String),
	request_write_access: Schema.optional(Schema.Boolean),
});
export type LoginUrl = typeof LoginUrl.Type;

/** This object represents an inline button that switches the current user to inline mode in a chosen chat, with an optional default inline query. */
export const SwitchInlineQueryChosenChat = Schema.Struct({
	query: Schema.optional(Schema.String),
	allow_user_chats: Schema.optional(Schema.Boolean),
	allow_bot_chats: Schema.optional(Schema.Boolean),
	allow_group_chats: Schema.optional(Schema.Boolean),
	allow_channel_chats: Schema.optional(Schema.Boolean),
});
export type SwitchInlineQueryChosenChat = typeof SwitchInlineQueryChosenChat.Type;

/** Describes a Web App. */
export const WebAppInfo = Schema.Struct({
	url: Schema.String,
});
export type WebAppInfo = typeof WebAppInfo.Type;

/** This object represents one button of an inline keyboard. Exactly one of the fields other than text, icon_custom_emoji_id, and style must be used to specify the type of the button. */
export const InlineKeyboardButton = Schema.Struct({
	text: Schema.String,
	icon_custom_emoji_id: Schema.optional(Schema.String),
	style: Schema.optional(Schema.String),
	url: Schema.optional(Schema.String),
	callback_data: Schema.optional(Schema.String),
	web_app: Schema.optional(WebAppInfo),
	login_url: Schema.optional(LoginUrl),
	switch_inline_query: Schema.optional(Schema.String),
	switch_inline_query_current_chat: Schema.optional(Schema.String),
	switch_inline_query_chosen_chat: Schema.optional(SwitchInlineQueryChosenChat),
	copy_text: Schema.optional(CopyTextButton),
	callback_game: Schema.optional(CallbackGame),
	pay: Schema.optional(Schema.Boolean),
});
export type InlineKeyboardButton = typeof InlineKeyboardButton.Type;

/** This object represents an inline keyboard that appears right next to the message it belongs to. */
export const InlineKeyboardMarkup = Schema.Struct({
	inline_keyboard: Schema.Array(Schema.Array(InlineKeyboardButton)),
});
export type InlineKeyboardMarkup = typeof InlineKeyboardMarkup.Type;

/** This object contains information about the bot that was created to be managed by the current bot. */
export const ManagedBotCreated = Schema.Struct({
	bot: User,
});
export type ManagedBotCreated = typeof ManagedBotCreated.Type;

/** This object represents a service message about a change in auto-delete timer settings. */
export const MessageAutoDeleteTimerChanged = Schema.Struct({
	message_auto_delete_time: Schema.Int,
});
export type MessageAutoDeleteTimerChanged = typeof MessageAutoDeleteTimerChanged.Type;

/** Describes a service message about a change in the price of paid messages within a chat. */
export const PaidMessagePriceChanged = Schema.Struct({
	paid_message_star_count: Schema.Int,
});
export type PaidMessagePriceChanged = typeof PaidMessagePriceChanged.Type;

/** Describes a service message about an option added to a poll. */
export const PollOptionAdded = Schema.Struct({
	poll_message: Schema.optional(MaybeInaccessibleMessage),
	option_persistent_id: Schema.String,
	option_text: Schema.String,
	option_text_entities: Schema.optional(Schema.Array(MessageEntity)),
});
export type PollOptionAdded = typeof PollOptionAdded.Type;

/** Describes a service message about an option deleted from a poll. */
export const PollOptionDeleted = Schema.Struct({
	poll_message: Schema.optional(MaybeInaccessibleMessage),
	option_persistent_id: Schema.String,
	option_text: Schema.String,
	option_text_entities: Schema.optional(Schema.Array(MessageEntity)),
});
export type PollOptionDeleted = typeof PollOptionDeleted.Type;

/** This object represents the content of a service message, sent whenever a user in the chat triggers a proximity alert set by another user. */
export const ProximityAlertTriggered = Schema.Struct({
	traveler: User,
	watcher: User,
	distance: Schema.Int,
});
export type ProximityAlertTriggered = typeof ProximityAlertTriggered.Type;

/** Describes the price of a suggested post. */
export const SuggestedPostPrice = Schema.Struct({
	currency: Schema.String,
	amount: Schema.Int,
});
export type SuggestedPostPrice = typeof SuggestedPostPrice.Type;

/** Contains information about a suggested post. */
export const SuggestedPostInfo = Schema.Struct({
	state: Schema.String,
	price: Schema.optional(SuggestedPostPrice),
	send_date: Schema.optional(Schema.Int),
});
export type SuggestedPostInfo = typeof SuggestedPostInfo.Type;

/** Describes an amount of Telegram Stars. */
export const StarAmount = Schema.Struct({
	amount: Schema.Int,
	nanostar_amount: Schema.optional(Schema.Int),
});
export type StarAmount = typeof StarAmount.Type;

/** This object contains information about the quoted part of a message that is replied to by the given message. */
export const TextQuote = Schema.Struct({
	text: Schema.String,
	entities: Schema.optional(Schema.Array(MessageEntity)),
	position: Schema.Int,
	is_manual: Schema.optional(Schema.Literal(true)),
});
export type TextQuote = typeof TextQuote.Type;

/** This object describes the colors of the backdrop of a unique gift. */
export const UniqueGiftBackdropColors = Schema.Struct({
	center_color: Schema.Int,
	edge_color: Schema.Int,
	symbol_color: Schema.Int,
	text_color: Schema.Int,
});
export type UniqueGiftBackdropColors = typeof UniqueGiftBackdropColors.Type;

/** This object describes the backdrop of a unique gift. */
export const UniqueGiftBackdrop = Schema.Struct({
	name: Schema.String,
	colors: UniqueGiftBackdropColors,
	rarity_per_mille: Schema.Int,
});
export type UniqueGiftBackdrop = typeof UniqueGiftBackdrop.Type;

/** This object contains information about the color scheme for a user's name, message replies and link previews based on a unique gift. */
export const UniqueGiftColors = Schema.Struct({
	model_custom_emoji_id: Schema.String,
	symbol_custom_emoji_id: Schema.String,
	light_theme_main_color: Schema.Int,
	light_theme_other_colors: Schema.Array(Schema.Int),
	dark_theme_main_color: Schema.Int,
	dark_theme_other_colors: Schema.Array(Schema.Int),
});
export type UniqueGiftColors = typeof UniqueGiftColors.Type;

/** This object describes the model of a unique gift. */
export const UniqueGiftModel = Schema.Struct({
	name: Schema.String,
	sticker: Sticker,
	rarity_per_mille: Schema.Int,
	rarity: Schema.optional(Schema.String),
});
export type UniqueGiftModel = typeof UniqueGiftModel.Type;

/** This object describes the symbol shown on the pattern of a unique gift. */
export const UniqueGiftSymbol = Schema.Struct({
	name: Schema.String,
	sticker: Sticker,
	rarity_per_mille: Schema.Int,
});
export type UniqueGiftSymbol = typeof UniqueGiftSymbol.Type;

/** This object describes a unique gift that was upgraded from a regular gift. */
export const UniqueGift = Schema.Struct({
	gift_id: Schema.String,
	base_name: Schema.String,
	name: Schema.String,
	number: Schema.Int,
	model: UniqueGiftModel,
	symbol: UniqueGiftSymbol,
	backdrop: UniqueGiftBackdrop,
	is_premium: Schema.optional(Schema.Literal(true)),
	is_burned: Schema.optional(Schema.Literal(true)),
	is_from_blockchain: Schema.optional(Schema.Literal(true)),
	colors: Schema.optional(UniqueGiftColors),
	publisher_chat: Schema.optional(Chat),
});
export type UniqueGift = typeof UniqueGift.Type;

/** Describes a service message about a unique gift that was sent or received. */
export const UniqueGiftInfo = Schema.Struct({
	gift: UniqueGift,
	origin: Schema.String,
	last_resale_currency: Schema.optional(Schema.String),
	last_resale_amount: Schema.optional(Schema.Int),
	owned_gift_id: Schema.optional(Schema.String),
	transfer_star_count: Schema.optional(Schema.Int),
	next_transfer_date: Schema.optional(Schema.Int),
});
export type UniqueGiftInfo = typeof UniqueGiftInfo.Type;

/** This object contains information about a user that was shared with the bot using a KeyboardButtonRequestUsers button. */
export const SharedUser = Schema.Struct({
	user_id: Schema.Int,
	first_name: Schema.optional(Schema.String),
	last_name: Schema.optional(Schema.String),
	username: Schema.optional(Schema.String),
	photo: Schema.optional(Schema.Array(PhotoSize)),
});
export type SharedUser = typeof SharedUser.Type;

/** This object contains information about the users whose identifiers were shared with the bot using a KeyboardButtonRequestUsers button. */
export const UsersShared = Schema.Struct({
	request_id: Schema.Int,
	users: Schema.Array(SharedUser),
});
export type UsersShared = typeof UsersShared.Type;

/** This object represents a service message about a video chat ended in the chat. */
export const VideoChatEnded = Schema.Struct({
	duration: Schema.Int,
});
export type VideoChatEnded = typeof VideoChatEnded.Type;

/** This object represents a service message about new members invited to a video chat. */
export const VideoChatParticipantsInvited = Schema.Struct({
	users: Schema.Array(User),
});
export type VideoChatParticipantsInvited = typeof VideoChatParticipantsInvited.Type;

/** This object represents a service message about a video chat scheduled in the chat. */
export const VideoChatScheduled = Schema.Struct({
	start_date: Schema.Int,
});
export type VideoChatScheduled = typeof VideoChatScheduled.Type;

/** Describes data sent from a Web App to the bot. */
export const WebAppData = Schema.Struct({
	data: Schema.String,
	button_text: Schema.String,
});
export type WebAppData = typeof WebAppData.Type;

/** This object represents a service message about a user allowing a bot to write messages after adding it to the attachment menu, launching a Web App from a link, or accepting an explicit request from a Web App sent by the method requestWriteAccess. */
export const WriteAccessAllowed = Schema.Struct({
	from_request: Schema.optional(Schema.Boolean),
	web_app_name: Schema.optional(Schema.String),
	from_attachment_menu: Schema.optional(Schema.Boolean),
});
export type WriteAccessAllowed = typeof WriteAccessAllowed.Type;

/** Describes a service message about tasks added to a checklist. */
export type ChecklistTasksAdded = {
	readonly checklist_message?: Message | undefined;
	readonly tasks: ReadonlyArray<ChecklistTask>;
};
export const ChecklistTasksAdded = Schema.Struct({
	checklist_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	tasks: Schema.Array(ChecklistTask),
});

/** Describes a service message about checklist tasks marked as done or not done. */
export type ChecklistTasksDone = {
	readonly checklist_message?: Message | undefined;
	readonly marked_as_done_task_ids?: ReadonlyArray<number> | undefined;
	readonly marked_as_not_done_task_ids?: ReadonlyArray<number> | undefined;
};
export const ChecklistTasksDone = Schema.Struct({
	checklist_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	marked_as_done_task_ids: Schema.optional(Schema.Array(Schema.Int)),
	marked_as_not_done_task_ids: Schema.optional(Schema.Array(Schema.Int)),
});

/** This object represents a service message about the completion of a giveaway without public winners. */
export type GiveawayCompleted = {
	readonly winner_count: number;
	readonly unclaimed_prize_count?: number | undefined;
	readonly giveaway_message?: Message | undefined;
	readonly is_star_giveaway?: true | undefined;
};
export const GiveawayCompleted = Schema.Struct({
	winner_count: Schema.Int,
	unclaimed_prize_count: Schema.optional(Schema.Int),
	giveaway_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	is_star_giveaway: Schema.optional(Schema.Literal(true)),
});

/** This object represents a message. */
export type Message = {
	readonly message_id: number;
	readonly message_thread_id?: number | undefined;
	readonly direct_messages_topic?: DirectMessagesTopic | undefined;
	readonly from?: User | undefined;
	readonly sender_chat?: Chat | undefined;
	readonly sender_boost_count?: number | undefined;
	readonly sender_business_bot?: User | undefined;
	readonly sender_tag?: string | undefined;
	readonly date: number;
	readonly guest_query_id?: string | undefined;
	readonly business_connection_id?: string | undefined;
	readonly chat: Chat;
	readonly forward_origin?: unknown;
	readonly is_topic_message?: true | undefined;
	readonly is_automatic_forward?: true | undefined;
	readonly reply_to_message?: Message | undefined;
	readonly external_reply?: ExternalReplyInfo | undefined;
	readonly quote?: TextQuote | undefined;
	readonly reply_to_story?: Story | undefined;
	readonly reply_to_checklist_task_id?: number | undefined;
	readonly reply_to_poll_option_id?: string | undefined;
	readonly via_bot?: User | undefined;
	readonly guest_bot_caller_user?: User | undefined;
	readonly guest_bot_caller_chat?: Chat | undefined;
	readonly edit_date?: number | undefined;
	readonly has_protected_content?: true | undefined;
	readonly is_from_offline?: true | undefined;
	readonly is_paid_post?: true | undefined;
	readonly media_group_id?: string | undefined;
	readonly author_signature?: string | undefined;
	readonly paid_star_count?: number | undefined;
	readonly text?: string | undefined;
	readonly entities?: ReadonlyArray<MessageEntity> | undefined;
	readonly link_preview_options?: LinkPreviewOptions | undefined;
	readonly suggested_post_info?: SuggestedPostInfo | undefined;
	readonly effect_id?: string | undefined;
	readonly animation?: Animation | undefined;
	readonly audio?: Audio | undefined;
	readonly document?: Document | undefined;
	readonly live_photo?: LivePhoto | undefined;
	readonly paid_media?: PaidMediaInfo | undefined;
	readonly photo?: ReadonlyArray<PhotoSize> | undefined;
	readonly sticker?: unknown;
	readonly story?: Story | undefined;
	readonly video?: Video | undefined;
	readonly video_note?: VideoNote | undefined;
	readonly voice?: Voice | undefined;
	readonly caption?: string | undefined;
	readonly caption_entities?: ReadonlyArray<MessageEntity> | undefined;
	readonly show_caption_above_media?: true | undefined;
	readonly has_media_spoiler?: true | undefined;
	readonly checklist?: Checklist | undefined;
	readonly contact?: Contact | undefined;
	readonly dice?: Dice | undefined;
	readonly game?: unknown;
	readonly poll?: Poll | undefined;
	readonly venue?: Venue | undefined;
	readonly location?: Location | undefined;
	readonly new_chat_members?: ReadonlyArray<User> | undefined;
	readonly left_chat_member?: User | undefined;
	readonly chat_owner_left?: ChatOwnerLeft | undefined;
	readonly chat_owner_changed?: ChatOwnerChanged | undefined;
	readonly new_chat_title?: string | undefined;
	readonly new_chat_photo?: ReadonlyArray<PhotoSize> | undefined;
	readonly delete_chat_photo?: true | undefined;
	readonly group_chat_created?: true | undefined;
	readonly supergroup_chat_created?: true | undefined;
	readonly channel_chat_created?: true | undefined;
	readonly message_auto_delete_timer_changed?: MessageAutoDeleteTimerChanged | undefined;
	readonly migrate_to_chat_id?: number | undefined;
	readonly migrate_from_chat_id?: number | undefined;
	readonly pinned_message?: unknown;
	readonly invoice?: unknown;
	readonly successful_payment?: unknown;
	readonly refunded_payment?: unknown;
	readonly users_shared?: UsersShared | undefined;
	readonly chat_shared?: ChatShared | undefined;
	readonly gift?: GiftInfo | undefined;
	readonly unique_gift?: UniqueGiftInfo | undefined;
	readonly gift_upgrade_sent?: GiftInfo | undefined;
	readonly connected_website?: string | undefined;
	readonly write_access_allowed?: WriteAccessAllowed | undefined;
	readonly passport_data?: unknown;
	readonly proximity_alert_triggered?: ProximityAlertTriggered | undefined;
	readonly boost_added?: ChatBoostAdded | undefined;
	readonly chat_background_set?: ChatBackground | undefined;
	readonly checklist_tasks_done?: ChecklistTasksDone | undefined;
	readonly checklist_tasks_added?: ChecklistTasksAdded | undefined;
	readonly direct_message_price_changed?: DirectMessagePriceChanged | undefined;
	readonly forum_topic_created?: ForumTopicCreated | undefined;
	readonly forum_topic_edited?: ForumTopicEdited | undefined;
	readonly forum_topic_closed?: unknown;
	readonly forum_topic_reopened?: unknown;
	readonly general_forum_topic_hidden?: unknown;
	readonly general_forum_topic_unhidden?: unknown;
	readonly giveaway_created?: GiveawayCreated | undefined;
	readonly giveaway?: Giveaway | undefined;
	readonly giveaway_winners?: GiveawayWinners | undefined;
	readonly giveaway_completed?: GiveawayCompleted | undefined;
	readonly managed_bot_created?: ManagedBotCreated | undefined;
	readonly paid_message_price_changed?: PaidMessagePriceChanged | undefined;
	readonly poll_option_added?: PollOptionAdded | undefined;
	readonly poll_option_deleted?: PollOptionDeleted | undefined;
	readonly suggested_post_approved?: SuggestedPostApproved | undefined;
	readonly suggested_post_approval_failed?: SuggestedPostApprovalFailed | undefined;
	readonly suggested_post_declined?: SuggestedPostDeclined | undefined;
	readonly suggested_post_paid?: SuggestedPostPaid | undefined;
	readonly suggested_post_refunded?: SuggestedPostRefunded | undefined;
	readonly video_chat_scheduled?: VideoChatScheduled | undefined;
	readonly video_chat_started?: unknown;
	readonly video_chat_ended?: VideoChatEnded | undefined;
	readonly video_chat_participants_invited?: VideoChatParticipantsInvited | undefined;
	readonly web_app_data?: WebAppData | undefined;
	readonly reply_markup?: InlineKeyboardMarkup | undefined;
};
export const Message = Schema.Struct({
	message_id: Schema.Int,
	message_thread_id: Schema.optional(Schema.Int),
	direct_messages_topic: Schema.optional(DirectMessagesTopic),
	from: Schema.optional(User),
	sender_chat: Schema.optional(Chat),
	sender_boost_count: Schema.optional(Schema.Int),
	sender_business_bot: Schema.optional(User),
	sender_tag: Schema.optional(Schema.String),
	date: Schema.Int,
	guest_query_id: Schema.optional(Schema.String),
	business_connection_id: Schema.optional(Schema.String),
	chat: Chat,
	forward_origin: Schema.optional(MessageOrigin),
	is_topic_message: Schema.optional(Schema.Literal(true)),
	is_automatic_forward: Schema.optional(Schema.Literal(true)),
	reply_to_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	external_reply: Schema.optional(ExternalReplyInfo),
	quote: Schema.optional(TextQuote),
	reply_to_story: Schema.optional(Story),
	reply_to_checklist_task_id: Schema.optional(Schema.Int),
	reply_to_poll_option_id: Schema.optional(Schema.String),
	via_bot: Schema.optional(User),
	guest_bot_caller_user: Schema.optional(User),
	guest_bot_caller_chat: Schema.optional(Chat),
	edit_date: Schema.optional(Schema.Int),
	has_protected_content: Schema.optional(Schema.Literal(true)),
	is_from_offline: Schema.optional(Schema.Literal(true)),
	is_paid_post: Schema.optional(Schema.Literal(true)),
	media_group_id: Schema.optional(Schema.String),
	author_signature: Schema.optional(Schema.String),
	paid_star_count: Schema.optional(Schema.Int),
	text: Schema.optional(Schema.String),
	entities: Schema.optional(Schema.Array(MessageEntity)),
	link_preview_options: Schema.optional(LinkPreviewOptions),
	suggested_post_info: Schema.optional(SuggestedPostInfo),
	effect_id: Schema.optional(Schema.String),
	animation: Schema.optional(Animation),
	audio: Schema.optional(Audio),
	document: Schema.optional(Document),
	live_photo: Schema.optional(LivePhoto),
	paid_media: Schema.optional(PaidMediaInfo),
	photo: Schema.optional(Schema.Array(PhotoSize)),
	sticker: Schema.optional(Sticker),
	story: Schema.optional(Story),
	video: Schema.optional(Video),
	video_note: Schema.optional(VideoNote),
	voice: Schema.optional(Voice),
	caption: Schema.optional(Schema.String),
	caption_entities: Schema.optional(Schema.Array(MessageEntity)),
	show_caption_above_media: Schema.optional(Schema.Literal(true)),
	has_media_spoiler: Schema.optional(Schema.Literal(true)),
	checklist: Schema.optional(Checklist),
	contact: Schema.optional(Contact),
	dice: Schema.optional(Dice),
	game: Schema.optional(Game),
	poll: Schema.optional(Poll),
	venue: Schema.optional(Venue),
	location: Schema.optional(Location),
	new_chat_members: Schema.optional(Schema.Array(User)),
	left_chat_member: Schema.optional(User),
	chat_owner_left: Schema.optional(ChatOwnerLeft),
	chat_owner_changed: Schema.optional(ChatOwnerChanged),
	new_chat_title: Schema.optional(Schema.String),
	new_chat_photo: Schema.optional(Schema.Array(PhotoSize)),
	delete_chat_photo: Schema.optional(Schema.Literal(true)),
	group_chat_created: Schema.optional(Schema.Literal(true)),
	supergroup_chat_created: Schema.optional(Schema.Literal(true)),
	channel_chat_created: Schema.optional(Schema.Literal(true)),
	message_auto_delete_timer_changed: Schema.optional(MessageAutoDeleteTimerChanged),
	migrate_to_chat_id: Schema.optional(Schema.Int),
	migrate_from_chat_id: Schema.optional(Schema.Int),
	pinned_message: Schema.optional(MaybeInaccessibleMessage),
	invoice: Schema.optional(Invoice),
	successful_payment: Schema.optional(SuccessfulPayment),
	refunded_payment: Schema.optional(RefundedPayment),
	users_shared: Schema.optional(UsersShared),
	chat_shared: Schema.optional(ChatShared),
	gift: Schema.optional(GiftInfo),
	unique_gift: Schema.optional(UniqueGiftInfo),
	gift_upgrade_sent: Schema.optional(GiftInfo),
	connected_website: Schema.optional(Schema.String),
	write_access_allowed: Schema.optional(WriteAccessAllowed),
	passport_data: Schema.optional(PassportData),
	proximity_alert_triggered: Schema.optional(ProximityAlertTriggered),
	boost_added: Schema.optional(ChatBoostAdded),
	chat_background_set: Schema.optional(ChatBackground),
	checklist_tasks_done: Schema.optional(Schema.suspend((): Schema.Codec<ChecklistTasksDone> => ChecklistTasksDone)),
	checklist_tasks_added: Schema.optional(Schema.suspend((): Schema.Codec<ChecklistTasksAdded> => ChecklistTasksAdded)),
	direct_message_price_changed: Schema.optional(DirectMessagePriceChanged),
	forum_topic_created: Schema.optional(ForumTopicCreated),
	forum_topic_edited: Schema.optional(ForumTopicEdited),
	forum_topic_closed: Schema.optional(ForumTopicClosed),
	forum_topic_reopened: Schema.optional(ForumTopicReopened),
	general_forum_topic_hidden: Schema.optional(GeneralForumTopicHidden),
	general_forum_topic_unhidden: Schema.optional(GeneralForumTopicUnhidden),
	giveaway_created: Schema.optional(GiveawayCreated),
	giveaway: Schema.optional(Giveaway),
	giveaway_winners: Schema.optional(GiveawayWinners),
	giveaway_completed: Schema.optional(Schema.suspend((): Schema.Codec<GiveawayCompleted> => GiveawayCompleted)),
	managed_bot_created: Schema.optional(ManagedBotCreated),
	paid_message_price_changed: Schema.optional(PaidMessagePriceChanged),
	poll_option_added: Schema.optional(PollOptionAdded),
	poll_option_deleted: Schema.optional(PollOptionDeleted),
	suggested_post_approved: Schema.optional(
		Schema.suspend((): Schema.Codec<SuggestedPostApproved> => SuggestedPostApproved),
	),
	suggested_post_approval_failed: Schema.optional(
		Schema.suspend((): Schema.Codec<SuggestedPostApprovalFailed> => SuggestedPostApprovalFailed),
	),
	suggested_post_declined: Schema.optional(
		Schema.suspend((): Schema.Codec<SuggestedPostDeclined> => SuggestedPostDeclined),
	),
	suggested_post_paid: Schema.optional(Schema.suspend((): Schema.Codec<SuggestedPostPaid> => SuggestedPostPaid)),
	suggested_post_refunded: Schema.optional(
		Schema.suspend((): Schema.Codec<SuggestedPostRefunded> => SuggestedPostRefunded),
	),
	video_chat_scheduled: Schema.optional(VideoChatScheduled),
	video_chat_started: Schema.optional(VideoChatStarted),
	video_chat_ended: Schema.optional(VideoChatEnded),
	video_chat_participants_invited: Schema.optional(VideoChatParticipantsInvited),
	web_app_data: Schema.optional(WebAppData),
	reply_markup: Schema.optional(InlineKeyboardMarkup),
});

/** Describes a service message about the failed approval of a suggested post. Currently, only caused by insufficient user funds at the time of approval. */
export type SuggestedPostApprovalFailed = {
	readonly suggested_post_message?: Message | undefined;
	readonly price: SuggestedPostPrice;
};
export const SuggestedPostApprovalFailed = Schema.Struct({
	suggested_post_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	price: SuggestedPostPrice,
});

/** Describes a service message about the approval of a suggested post. */
export type SuggestedPostApproved = {
	readonly suggested_post_message?: Message | undefined;
	readonly price?: SuggestedPostPrice | undefined;
	readonly send_date: number;
};
export const SuggestedPostApproved = Schema.Struct({
	suggested_post_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	price: Schema.optional(SuggestedPostPrice),
	send_date: Schema.Int,
});

/** Describes a service message about the rejection of a suggested post. */
export type SuggestedPostDeclined = {
	readonly suggested_post_message?: Message | undefined;
	readonly comment?: string | undefined;
};
export const SuggestedPostDeclined = Schema.Struct({
	suggested_post_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	comment: Schema.optional(Schema.String),
});

/** Describes a service message about a successful payment for a suggested post. */
export type SuggestedPostPaid = {
	readonly suggested_post_message?: Message | undefined;
	readonly currency: string;
	readonly amount?: number | undefined;
	readonly star_amount?: StarAmount | undefined;
};
export const SuggestedPostPaid = Schema.Struct({
	suggested_post_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	currency: Schema.String,
	amount: Schema.optional(Schema.Int),
	star_amount: Schema.optional(StarAmount),
});

/** Describes a service message about a payment refund for a suggested post. */
export type SuggestedPostRefunded = {
	readonly suggested_post_message?: Message | undefined;
	readonly reason: string;
};
export const SuggestedPostRefunded = Schema.Struct({
	suggested_post_message: Schema.optional(Schema.suspend((): Schema.Codec<Message> => Message)),
	reason: Schema.String,
});

/** This object describes the rating of a user based on their Telegram Star spendings. */
export const UserRating = Schema.Struct({
	level: Schema.Int,
	rating: Schema.Int,
	current_level_rating: Schema.Int,
	next_level_rating: Schema.optional(Schema.Int),
});
export type UserRating = typeof UserRating.Type;

/** This object contains full information about a chat. */
export const ChatFullInfo = Schema.Struct({
	id: Schema.Int,
	type: Schema.String,
	title: Schema.optional(Schema.String),
	username: Schema.optional(Schema.String),
	first_name: Schema.optional(Schema.String),
	last_name: Schema.optional(Schema.String),
	is_forum: Schema.optional(Schema.Literal(true)),
	is_direct_messages: Schema.optional(Schema.Literal(true)),
	accent_color_id: Schema.Int,
	max_reaction_count: Schema.Int,
	photo: Schema.optional(ChatPhoto),
	active_usernames: Schema.optional(Schema.Array(Schema.String)),
	birthdate: Schema.optional(Birthdate),
	business_intro: Schema.optional(BusinessIntro),
	business_location: Schema.optional(BusinessLocation),
	business_opening_hours: Schema.optional(BusinessOpeningHours),
	personal_chat: Schema.optional(Chat),
	parent_chat: Schema.optional(Chat),
	available_reactions: Schema.optional(Schema.Array(ReactionType)),
	background_custom_emoji_id: Schema.optional(Schema.String),
	profile_accent_color_id: Schema.optional(Schema.Int),
	profile_background_custom_emoji_id: Schema.optional(Schema.String),
	emoji_status_custom_emoji_id: Schema.optional(Schema.String),
	emoji_status_expiration_date: Schema.optional(Schema.Int),
	bio: Schema.optional(Schema.String),
	has_private_forwards: Schema.optional(Schema.Literal(true)),
	has_restricted_voice_and_video_messages: Schema.optional(Schema.Literal(true)),
	join_to_send_messages: Schema.optional(Schema.Literal(true)),
	join_by_request: Schema.optional(Schema.Literal(true)),
	description: Schema.optional(Schema.String),
	invite_link: Schema.optional(Schema.String),
	pinned_message: Schema.optional(Message),
	permissions: Schema.optional(ChatPermissions),
	accepted_gift_types: AcceptedGiftTypes,
	can_send_paid_media: Schema.optional(Schema.Literal(true)),
	slow_mode_delay: Schema.optional(Schema.Int),
	unrestrict_boost_count: Schema.optional(Schema.Int),
	message_auto_delete_time: Schema.optional(Schema.Int),
	has_aggressive_anti_spam_enabled: Schema.optional(Schema.Literal(true)),
	has_hidden_members: Schema.optional(Schema.Literal(true)),
	has_protected_content: Schema.optional(Schema.Literal(true)),
	has_visible_history: Schema.optional(Schema.Literal(true)),
	sticker_set_name: Schema.optional(Schema.String),
	can_set_sticker_set: Schema.optional(Schema.Literal(true)),
	custom_emoji_sticker_set_name: Schema.optional(Schema.String),
	linked_chat_id: Schema.optional(Schema.Int),
	location: Schema.optional(ChatLocation),
	rating: Schema.optional(UserRating),
	first_profile_audio: Schema.optional(Audio),
	unique_gift_colors: Schema.optional(UniqueGiftColors),
	paid_message_star_count: Schema.optional(Schema.Int),
});
export type ChatFullInfo = typeof ChatFullInfo.Type;

/** Represents an invite link for a chat. */
export const ChatInviteLink = Schema.Struct({
	invite_link: Schema.String,
	creator: User,
	creates_join_request: Schema.Boolean,
	is_primary: Schema.Boolean,
	is_revoked: Schema.Boolean,
	name: Schema.optional(Schema.String),
	expire_date: Schema.optional(Schema.Int),
	member_limit: Schema.optional(Schema.Int),
	pending_join_request_count: Schema.optional(Schema.Int),
	subscription_period: Schema.optional(Schema.Int),
	subscription_price: Schema.optional(Schema.Int),
});
export type ChatInviteLink = typeof ChatInviteLink.Type;

/** Represents a join request sent to a chat. */
export const ChatJoinRequest = Schema.Struct({
	chat: Chat,
	from: User,
	user_chat_id: Schema.Int,
	date: Schema.Int,
	bio: Schema.optional(Schema.String),
	invite_link: Schema.optional(ChatInviteLink),
});
export type ChatJoinRequest = typeof ChatJoinRequest.Type;

/** Represents a chat member that has some additional privileges. */
export const ChatMemberAdministrator = Schema.Struct({
	status: Schema.String,
	user: User,
	can_be_edited: Schema.Boolean,
	is_anonymous: Schema.Boolean,
	can_manage_chat: Schema.Boolean,
	can_delete_messages: Schema.Boolean,
	can_manage_video_chats: Schema.Boolean,
	can_restrict_members: Schema.Boolean,
	can_promote_members: Schema.Boolean,
	can_change_info: Schema.Boolean,
	can_invite_users: Schema.Boolean,
	can_post_stories: Schema.Boolean,
	can_edit_stories: Schema.Boolean,
	can_delete_stories: Schema.Boolean,
	can_post_messages: Schema.optional(Schema.Boolean),
	can_edit_messages: Schema.optional(Schema.Boolean),
	can_pin_messages: Schema.optional(Schema.Boolean),
	can_manage_topics: Schema.optional(Schema.Boolean),
	can_manage_direct_messages: Schema.optional(Schema.Boolean),
	can_manage_tags: Schema.optional(Schema.Boolean),
	custom_title: Schema.optional(Schema.String),
});
export type ChatMemberAdministrator = typeof ChatMemberAdministrator.Type;

/** Represents a chat member that was banned in the chat and can't return to the chat or view chat messages. */
export const ChatMemberBanned = Schema.Struct({
	status: Schema.String,
	user: User,
	until_date: Schema.Int,
});
export type ChatMemberBanned = typeof ChatMemberBanned.Type;

/** Represents a chat member that isn't currently a member of the chat, but may join it themselves. */
export const ChatMemberLeft = Schema.Struct({
	status: Schema.String,
	user: User,
});
export type ChatMemberLeft = typeof ChatMemberLeft.Type;

/** Represents a chat member that has no additional privileges or restrictions. */
export const ChatMemberMember = Schema.Struct({
	status: Schema.String,
	tag: Schema.optional(Schema.String),
	user: User,
	until_date: Schema.optional(Schema.Int),
});
export type ChatMemberMember = typeof ChatMemberMember.Type;

/** Represents a chat member that owns the chat and has all administrator privileges. */
export const ChatMemberOwner = Schema.Struct({
	status: Schema.String,
	user: User,
	is_anonymous: Schema.Boolean,
	custom_title: Schema.optional(Schema.String),
});
export type ChatMemberOwner = typeof ChatMemberOwner.Type;

/** Represents a chat member that is under certain restrictions in the chat. Supergroups only. */
export const ChatMemberRestricted = Schema.Struct({
	status: Schema.String,
	tag: Schema.optional(Schema.String),
	user: User,
	is_member: Schema.Boolean,
	can_send_messages: Schema.Boolean,
	can_send_audios: Schema.Boolean,
	can_send_documents: Schema.Boolean,
	can_send_photos: Schema.Boolean,
	can_send_videos: Schema.Boolean,
	can_send_video_notes: Schema.Boolean,
	can_send_voice_notes: Schema.Boolean,
	can_send_polls: Schema.Boolean,
	can_send_other_messages: Schema.Boolean,
	can_add_web_page_previews: Schema.Boolean,
	can_react_to_messages: Schema.Boolean,
	can_edit_tag: Schema.Boolean,
	can_change_info: Schema.Boolean,
	can_invite_users: Schema.Boolean,
	can_pin_messages: Schema.Boolean,
	can_manage_topics: Schema.Boolean,
	until_date: Schema.Int,
});
export type ChatMemberRestricted = typeof ChatMemberRestricted.Type;

/** This object represents changes in the status of a chat member. */
export const ChatMemberUpdated = Schema.Struct({
	chat: Chat,
	from: User,
	date: Schema.Int,
	old_chat_member: ChatMember,
	new_chat_member: ChatMember,
	invite_link: Schema.optional(ChatInviteLink),
	via_join_request: Schema.optional(Schema.Boolean),
	via_chat_folder_invite_link: Schema.optional(Schema.Boolean),
});
export type ChatMemberUpdated = typeof ChatMemberUpdated.Type;

/** This object represents a file ready to be downloaded. The file can be downloaded via the link https://api.telegram.org/file/bot<token>/<file_path>. It is guaranteed that the link will be valid for at least 1 hour. When the link expires, a new one can be requested by calling getFile. */
export const File = Schema.Struct({
	file_id: Schema.String,
	file_unique_id: Schema.String,
	file_size: Schema.optional(Schema.Int),
	file_path: Schema.optional(Schema.String),
});
export type File = typeof File.Type;

/** Upon receiving a message with this object, Telegram clients will display a reply interface to the user (act as if the user has selected the bot's message and tapped 'Reply'). This can be extremely useful if you want to create user-friendly step-by-step interfaces without having to sacrifice privacy mode. Not supported in channels and for messages sent on behalf of a user account. */
export const ForceReply = Schema.Struct({
	force_reply: Schema.Literal(true),
	input_field_placeholder: Schema.optional(Schema.String),
	selective: Schema.optional(Schema.Boolean),
});
export type ForceReply = typeof ForceReply.Type;

/** This object represents a forum topic. */
export const ForumTopic = Schema.Struct({
	message_thread_id: Schema.Int,
	name: Schema.String,
	icon_color: Schema.Int,
	icon_custom_emoji_id: Schema.optional(Schema.String),
	is_name_implicit: Schema.optional(Schema.Literal(true)),
});
export type ForumTopic = typeof ForumTopic.Type;

/** This object represent a list of gifts. */
export const Gifts = Schema.Struct({
	gifts: Schema.Array(Gift),
});
export type Gifts = typeof Gifts.Type;

/** This object describes a message that was deleted or is otherwise inaccessible to the bot. */
export const InaccessibleMessage = Schema.Struct({
	chat: Chat,
	message_id: Schema.Int,
	date: Schema.Int,
});
export type InaccessibleMessage = typeof InaccessibleMessage.Type;

/** Describes a task to add to a checklist. */
export const InputChecklistTask = Schema.Struct({
	id: Schema.Int,
	text: Schema.String,
	parse_mode: Schema.optional(Schema.String),
	text_entities: Schema.optional(Schema.Array(MessageEntity)),
});
export type InputChecklistTask = typeof InputChecklistTask.Type;

/** Describes a checklist to create. */
export const InputChecklist = Schema.Struct({
	title: Schema.String,
	parse_mode: Schema.optional(Schema.String),
	title_entities: Schema.optional(Schema.Array(MessageEntity)),
	tasks: Schema.Array(InputChecklistTask),
	others_can_add_tasks: Schema.optional(Schema.Boolean),
	others_can_mark_tasks_as_done: Schema.optional(Schema.Boolean),
});
export type InputChecklist = typeof InputChecklist.Type;

/** Represents an animation file (GIF or H.264/MPEG-4 AVC video without sound) to be sent. */
export const InputMediaAnimation = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	thumbnail: Schema.optional(Schema.String),
	caption: Schema.optional(Schema.String),
	parse_mode: Schema.optional(Schema.String),
	caption_entities: Schema.optional(Schema.Array(MessageEntity)),
	show_caption_above_media: Schema.optional(Schema.Boolean),
	width: Schema.optional(Schema.Int),
	height: Schema.optional(Schema.Int),
	duration: Schema.optional(Schema.Int),
	has_spoiler: Schema.optional(Schema.Boolean),
});
export type InputMediaAnimation = typeof InputMediaAnimation.Type;

/** Represents an audio file to be treated as music to be sent. */
export const InputMediaAudio = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	thumbnail: Schema.optional(Schema.String),
	caption: Schema.optional(Schema.String),
	parse_mode: Schema.optional(Schema.String),
	caption_entities: Schema.optional(Schema.Array(MessageEntity)),
	duration: Schema.optional(Schema.Int),
	performer: Schema.optional(Schema.String),
	title: Schema.optional(Schema.String),
});
export type InputMediaAudio = typeof InputMediaAudio.Type;

/** Represents a general file to be sent. */
export const InputMediaDocument = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	thumbnail: Schema.optional(Schema.String),
	caption: Schema.optional(Schema.String),
	parse_mode: Schema.optional(Schema.String),
	caption_entities: Schema.optional(Schema.Array(MessageEntity)),
	disable_content_type_detection: Schema.optional(Schema.Boolean),
});
export type InputMediaDocument = typeof InputMediaDocument.Type;

/** Represents a live photo to be sent. */
export const InputMediaLivePhoto = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	photo: Schema.String,
	caption: Schema.optional(Schema.String),
	parse_mode: Schema.optional(Schema.String),
	caption_entities: Schema.optional(Schema.Array(MessageEntity)),
	show_caption_above_media: Schema.optional(Schema.Boolean),
	has_spoiler: Schema.optional(Schema.Boolean),
});
export type InputMediaLivePhoto = typeof InputMediaLivePhoto.Type;

/** Represents a location to be sent. */
export const InputMediaLocation = Schema.Struct({
	type: Schema.String,
	latitude: Schema.Number,
	longitude: Schema.Number,
	horizontal_accuracy: Schema.optional(Schema.Number),
});
export type InputMediaLocation = typeof InputMediaLocation.Type;

/** Represents a photo to be sent. */
export const InputMediaPhoto = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	caption: Schema.optional(Schema.String),
	parse_mode: Schema.optional(Schema.String),
	caption_entities: Schema.optional(Schema.Array(MessageEntity)),
	show_caption_above_media: Schema.optional(Schema.Boolean),
	has_spoiler: Schema.optional(Schema.Boolean),
});
export type InputMediaPhoto = typeof InputMediaPhoto.Type;

/** Represents a sticker file to be sent. */
export const InputMediaSticker = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	emoji: Schema.optional(Schema.String),
});
export type InputMediaSticker = typeof InputMediaSticker.Type;

/** Represents a venue to be sent. */
export const InputMediaVenue = Schema.Struct({
	type: Schema.String,
	latitude: Schema.Number,
	longitude: Schema.Number,
	title: Schema.String,
	address: Schema.String,
	foursquare_id: Schema.optional(Schema.String),
	foursquare_type: Schema.optional(Schema.String),
	google_place_id: Schema.optional(Schema.String),
	google_place_type: Schema.optional(Schema.String),
});
export type InputMediaVenue = typeof InputMediaVenue.Type;

/** Represents a video to be sent. */
export const InputMediaVideo = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	thumbnail: Schema.optional(Schema.String),
	cover: Schema.optional(Schema.String),
	start_timestamp: Schema.optional(Schema.Int),
	caption: Schema.optional(Schema.String),
	parse_mode: Schema.optional(Schema.String),
	caption_entities: Schema.optional(Schema.Array(MessageEntity)),
	show_caption_above_media: Schema.optional(Schema.Boolean),
	width: Schema.optional(Schema.Int),
	height: Schema.optional(Schema.Int),
	duration: Schema.optional(Schema.Int),
	supports_streaming: Schema.optional(Schema.Boolean),
	has_spoiler: Schema.optional(Schema.Boolean),
});
export type InputMediaVideo = typeof InputMediaVideo.Type;

/** The paid media to send is a live photo. */
export const InputPaidMediaLivePhoto = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	photo: Schema.String,
});
export type InputPaidMediaLivePhoto = typeof InputPaidMediaLivePhoto.Type;

/** The paid media to send is a photo. */
export const InputPaidMediaPhoto = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
});
export type InputPaidMediaPhoto = typeof InputPaidMediaPhoto.Type;

/** The paid media to send is a video. */
export const InputPaidMediaVideo = Schema.Struct({
	type: Schema.String,
	media: Schema.String,
	thumbnail: Schema.optional(Schema.String),
	cover: Schema.optional(Schema.String),
	start_timestamp: Schema.optional(Schema.Int),
	width: Schema.optional(Schema.Int),
	height: Schema.optional(Schema.Int),
	duration: Schema.optional(Schema.Int),
	supports_streaming: Schema.optional(Schema.Boolean),
});
export type InputPaidMediaVideo = typeof InputPaidMediaVideo.Type;

/** This object contains information about one answer option in a poll to be sent. */
export const InputPollOption = Schema.Struct({
	text: Schema.String,
	text_parse_mode: Schema.optional(Schema.String),
	text_entities: Schema.optional(Schema.Array(MessageEntity)),
	media: Schema.optional(InputPollOptionMedia),
});
export type InputPollOption = typeof InputPollOption.Type;

/** An animated profile photo in the MPEG4 format. */
export const InputProfilePhotoAnimated = Schema.Struct({
	type: Schema.String,
	animation: Schema.String,
	main_frame_timestamp: Schema.optional(Schema.Number),
});
export type InputProfilePhotoAnimated = typeof InputProfilePhotoAnimated.Type;

/** A static profile photo in the .JPG format. */
export const InputProfilePhotoStatic = Schema.Struct({
	type: Schema.String,
	photo: Schema.String,
});
export type InputProfilePhotoStatic = typeof InputProfilePhotoStatic.Type;

/** Describes a photo to post as a story. */
export const InputStoryContentPhoto = Schema.Struct({
	type: Schema.String,
	photo: Schema.String,
});
export type InputStoryContentPhoto = typeof InputStoryContentPhoto.Type;

/** Describes a video to post as a story. */
export const InputStoryContentVideo = Schema.Struct({
	type: Schema.String,
	video: Schema.String,
	duration: Schema.optional(Schema.Number),
	cover_frame_timestamp: Schema.optional(Schema.Number),
	is_animation: Schema.optional(Schema.Boolean),
});
export type InputStoryContentVideo = typeof InputStoryContentVideo.Type;

/** This object represents type of a poll, which is allowed to be created and sent when the corresponding button is pressed. */
export const KeyboardButtonPollType = Schema.Struct({
	type: Schema.optional(Schema.String),
});
export type KeyboardButtonPollType = typeof KeyboardButtonPollType.Type;

/** This object defines the criteria used to request a suitable chat. Information about the selected chat will be shared with the bot when the corresponding button is pressed. The bot will be granted requested rights in the chat if appropriate. More about requesting chats ». */
export const KeyboardButtonRequestChat = Schema.Struct({
	request_id: Schema.Int,
	chat_is_channel: Schema.Boolean,
	chat_is_forum: Schema.optional(Schema.Boolean),
	chat_has_username: Schema.optional(Schema.Boolean),
	chat_is_created: Schema.optional(Schema.Boolean),
	user_administrator_rights: Schema.optional(ChatAdministratorRights),
	bot_administrator_rights: Schema.optional(ChatAdministratorRights),
	bot_is_member: Schema.optional(Schema.Boolean),
	request_title: Schema.optional(Schema.Boolean),
	request_username: Schema.optional(Schema.Boolean),
	request_photo: Schema.optional(Schema.Boolean),
});
export type KeyboardButtonRequestChat = typeof KeyboardButtonRequestChat.Type;

/** This object defines the parameters for the creation of a managed bot. Information about the created bot will be shared with the bot using the update managed_bot and a Message with the field managed_bot_created. */
export const KeyboardButtonRequestManagedBot = Schema.Struct({
	request_id: Schema.Int,
	suggested_name: Schema.optional(Schema.String),
	suggested_username: Schema.optional(Schema.String),
});
export type KeyboardButtonRequestManagedBot = typeof KeyboardButtonRequestManagedBot.Type;

/** This object defines the criteria used to request suitable users. Information about the selected users will be shared with the bot when the corresponding button is pressed. More about requesting users » */
export const KeyboardButtonRequestUsers = Schema.Struct({
	request_id: Schema.Int,
	user_is_bot: Schema.optional(Schema.Boolean),
	user_is_premium: Schema.optional(Schema.Boolean),
	max_quantity: Schema.optional(Schema.Int),
	request_name: Schema.optional(Schema.Boolean),
	request_username: Schema.optional(Schema.Boolean),
	request_photo: Schema.optional(Schema.Boolean),
});
export type KeyboardButtonRequestUsers = typeof KeyboardButtonRequestUsers.Type;

/** This object represents one button of the reply keyboard. At most one of the fields other than text, icon_custom_emoji_id, and style must be used to specify the type of the button. For simple text buttons, String can be used instead of this object to specify the button text. */
export const KeyboardButton = Schema.Struct({
	text: Schema.String,
	icon_custom_emoji_id: Schema.optional(Schema.String),
	style: Schema.optional(Schema.String),
	request_users: Schema.optional(KeyboardButtonRequestUsers),
	request_chat: Schema.optional(KeyboardButtonRequestChat),
	request_managed_bot: Schema.optional(KeyboardButtonRequestManagedBot),
	request_contact: Schema.optional(Schema.Boolean),
	request_location: Schema.optional(Schema.Boolean),
	request_poll: Schema.optional(KeyboardButtonPollType),
	web_app: Schema.optional(WebAppInfo),
});
export type KeyboardButton = typeof KeyboardButton.Type;

/** Describes the physical address of a location. */
export const LocationAddress = Schema.Struct({
	country_code: Schema.String,
	state: Schema.optional(Schema.String),
	city: Schema.optional(Schema.String),
	street: Schema.optional(Schema.String),
});
export type LocationAddress = typeof LocationAddress.Type;

/** This object contains information about the creation, token update, or owner update of a bot that is managed by the current bot. */
export const ManagedBotUpdated = Schema.Struct({
	user: User,
	bot: User,
});
export type ManagedBotUpdated = typeof ManagedBotUpdated.Type;

/** Represents a menu button, which opens the bot's list of commands. */
export const MenuButtonCommands = Schema.Struct({
	type: Schema.String,
});
export type MenuButtonCommands = typeof MenuButtonCommands.Type;

/** Describes that no specific value for the menu button was set. */
export const MenuButtonDefault = Schema.Struct({
	type: Schema.String,
});
export type MenuButtonDefault = typeof MenuButtonDefault.Type;

/** Represents a menu button, which launches a Web App. */
export const MenuButtonWebApp = Schema.Struct({
	type: Schema.String,
	text: Schema.String,
	web_app: WebAppInfo,
});
export type MenuButtonWebApp = typeof MenuButtonWebApp.Type;

/** This object represents a unique message identifier. */
export const MessageId = Schema.Struct({
	message_id: Schema.Int,
});
export type MessageId = typeof MessageId.Type;

/** The message was originally sent to a channel chat. */
export const MessageOriginChannel = Schema.Struct({
	type: Schema.String,
	date: Schema.Int,
	chat: Chat,
	message_id: Schema.Int,
	author_signature: Schema.optional(Schema.String),
});
export type MessageOriginChannel = typeof MessageOriginChannel.Type;

/** The message was originally sent on behalf of a chat to a group chat. */
export const MessageOriginChat = Schema.Struct({
	type: Schema.String,
	date: Schema.Int,
	sender_chat: Chat,
	author_signature: Schema.optional(Schema.String),
});
export type MessageOriginChat = typeof MessageOriginChat.Type;

/** The message was originally sent by an unknown user. */
export const MessageOriginHiddenUser = Schema.Struct({
	type: Schema.String,
	date: Schema.Int,
	sender_user_name: Schema.String,
});
export type MessageOriginHiddenUser = typeof MessageOriginHiddenUser.Type;

/** The message was originally sent by a known user. */
export const MessageOriginUser = Schema.Struct({
	type: Schema.String,
	date: Schema.Int,
	sender_user: User,
});
export type MessageOriginUser = typeof MessageOriginUser.Type;

/** Represents a reaction added to a message along with the number of times it was added. */
export const ReactionCount = Schema.Struct({
	type: ReactionType,
	total_count: Schema.Int,
});
export type ReactionCount = typeof ReactionCount.Type;

/** This object represents reaction changes on a message with anonymous reactions. */
export const MessageReactionCountUpdated = Schema.Struct({
	chat: Chat,
	message_id: Schema.Int,
	date: Schema.Int,
	reactions: Schema.Array(ReactionCount),
});
export type MessageReactionCountUpdated = typeof MessageReactionCountUpdated.Type;

/** This object represents a change of a reaction on a message performed by a user. */
export const MessageReactionUpdated = Schema.Struct({
	chat: Chat,
	message_id: Schema.Int,
	user: Schema.optional(User),
	actor_chat: Schema.optional(Chat),
	date: Schema.Int,
	old_reaction: Schema.Array(ReactionType),
	new_reaction: Schema.Array(ReactionType),
});
export type MessageReactionUpdated = typeof MessageReactionUpdated.Type;

/** Describes a regular gift owned by a user or a chat. */
export const OwnedGiftRegular = Schema.Struct({
	type: Schema.String,
	gift: Gift,
	owned_gift_id: Schema.optional(Schema.String),
	sender_user: Schema.optional(User),
	send_date: Schema.Int,
	text: Schema.optional(Schema.String),
	entities: Schema.optional(Schema.Array(MessageEntity)),
	is_private: Schema.optional(Schema.Literal(true)),
	is_saved: Schema.optional(Schema.Literal(true)),
	can_be_upgraded: Schema.optional(Schema.Literal(true)),
	was_refunded: Schema.optional(Schema.Literal(true)),
	convert_star_count: Schema.optional(Schema.Int),
	prepaid_upgrade_star_count: Schema.optional(Schema.Int),
	is_upgrade_separate: Schema.optional(Schema.Literal(true)),
	unique_gift_number: Schema.optional(Schema.Int),
});
export type OwnedGiftRegular = typeof OwnedGiftRegular.Type;

/** Describes a unique gift received and owned by a user or a chat. */
export const OwnedGiftUnique = Schema.Struct({
	type: Schema.String,
	gift: UniqueGift,
	owned_gift_id: Schema.optional(Schema.String),
	sender_user: Schema.optional(User),
	send_date: Schema.Int,
	is_saved: Schema.optional(Schema.Literal(true)),
	can_be_transferred: Schema.optional(Schema.Literal(true)),
	transfer_star_count: Schema.optional(Schema.Int),
	next_transfer_date: Schema.optional(Schema.Int),
});
export type OwnedGiftUnique = typeof OwnedGiftUnique.Type;

/** Contains the list of gifts received and owned by a user or a chat. */
export const OwnedGifts = Schema.Struct({
	total_count: Schema.Int,
	gifts: Schema.Array(OwnedGift),
	next_offset: Schema.optional(Schema.String),
});
export type OwnedGifts = typeof OwnedGifts.Type;

/** The paid media is a live photo. */
export const PaidMediaLivePhoto = Schema.Struct({
	type: Schema.String,
	live_photo: LivePhoto,
});
export type PaidMediaLivePhoto = typeof PaidMediaLivePhoto.Type;

/** The paid media is a photo. */
export const PaidMediaPhoto = Schema.Struct({
	type: Schema.String,
	photo: Schema.Array(PhotoSize),
});
export type PaidMediaPhoto = typeof PaidMediaPhoto.Type;

/** The paid media isn't available before the payment. */
export const PaidMediaPreview = Schema.Struct({
	type: Schema.String,
	width: Schema.optional(Schema.Int),
	height: Schema.optional(Schema.Int),
	duration: Schema.optional(Schema.Int),
});
export type PaidMediaPreview = typeof PaidMediaPreview.Type;

/** The paid media is a video. */
export const PaidMediaVideo = Schema.Struct({
	type: Schema.String,
	video: Video,
});
export type PaidMediaVideo = typeof PaidMediaVideo.Type;

/** This object represents an answer of a user in a non-anonymous poll. */
export const PollAnswer = Schema.Struct({
	poll_id: Schema.String,
	voter_chat: Schema.optional(Chat),
	user: Schema.optional(User),
	option_ids: Schema.Array(Schema.Int),
	option_persistent_ids: Schema.Array(Schema.String),
});
export type PollAnswer = typeof PollAnswer.Type;

/** Describes an inline message to be sent by a user of a Mini App. */
export const PreparedInlineMessage = Schema.Struct({
	id: Schema.String,
	expiration_date: Schema.Int,
});
export type PreparedInlineMessage = typeof PreparedInlineMessage.Type;

/** Describes a keyboard button to be used by a user of a Mini App. */
export const PreparedKeyboardButton = Schema.Struct({
	id: Schema.String,
});
export type PreparedKeyboardButton = typeof PreparedKeyboardButton.Type;

/** The reaction is based on a custom emoji. */
export const ReactionTypeCustomEmoji = Schema.Struct({
	type: Schema.String,
	custom_emoji_id: Schema.String,
});
export type ReactionTypeCustomEmoji = typeof ReactionTypeCustomEmoji.Type;

/** The reaction is based on an emoji. */
export const ReactionTypeEmoji = Schema.Struct({
	type: Schema.String,
	emoji: Schema.String,
});
export type ReactionTypeEmoji = typeof ReactionTypeEmoji.Type;

/** The reaction is paid. */
export const ReactionTypePaid = Schema.Struct({
	type: Schema.String,
});
export type ReactionTypePaid = typeof ReactionTypePaid.Type;

/** This object represents a custom keyboard with reply options (see Introduction to bots for details and examples). Not supported in channels and for messages sent on behalf of a business account. */
export const ReplyKeyboardMarkup = Schema.Struct({
	keyboard: Schema.Array(Schema.Array(KeyboardButton)),
	is_persistent: Schema.optional(Schema.Boolean),
	resize_keyboard: Schema.optional(Schema.Boolean),
	one_time_keyboard: Schema.optional(Schema.Boolean),
	input_field_placeholder: Schema.optional(Schema.String),
	selective: Schema.optional(Schema.Boolean),
});
export type ReplyKeyboardMarkup = typeof ReplyKeyboardMarkup.Type;

/** Upon receiving a message with this object, Telegram clients will remove the current custom keyboard and display the default letter-keyboard. By default, custom keyboards are displayed until a new keyboard is sent by a bot. An exception is made for one-time keyboards that are hidden immediately after the user presses a button (see ReplyKeyboardMarkup). Not supported in channels and for messages sent on behalf of a business account. */
export const ReplyKeyboardRemove = Schema.Struct({
	remove_keyboard: Schema.Literal(true),
	selective: Schema.optional(Schema.Boolean),
});
export type ReplyKeyboardRemove = typeof ReplyKeyboardRemove.Type;

/** Describes reply parameters for the message that is being sent. */
export const ReplyParameters = Schema.Struct({
	message_id: Schema.Int,
	chat_id: Schema.optional(Schema.Union([Schema.Int, Schema.String])),
	allow_sending_without_reply: Schema.optional(Schema.Boolean),
	quote: Schema.optional(Schema.String),
	quote_parse_mode: Schema.optional(Schema.String),
	quote_entities: Schema.optional(Schema.Array(MessageEntity)),
	quote_position: Schema.optional(Schema.Int),
	checklist_task_id: Schema.optional(Schema.Int),
	poll_option_id: Schema.optional(Schema.String),
});
export type ReplyParameters = typeof ReplyParameters.Type;

/** Describes why a request was unsuccessful. */
export const ResponseParameters = Schema.Struct({
	migrate_to_chat_id: Schema.optional(Schema.Int),
	retry_after: Schema.optional(Schema.Int),
});
export type ResponseParameters = typeof ResponseParameters.Type;

/** Describes an inline message sent by a guest bot. */
export const SentGuestMessage = Schema.Struct({
	inline_message_id: Schema.String,
});
export type SentGuestMessage = typeof SentGuestMessage.Type;

/** Describes an inline message sent by a Web App on behalf of a user. */
export const SentWebAppMessage = Schema.Struct({
	inline_message_id: Schema.optional(Schema.String),
});
export type SentWebAppMessage = typeof SentWebAppMessage.Type;

/** Describes the position of a clickable area within a story. */
export const StoryAreaPosition = Schema.Struct({
	x_percentage: Schema.Number,
	y_percentage: Schema.Number,
	width_percentage: Schema.Number,
	height_percentage: Schema.Number,
	rotation_angle: Schema.Number,
	corner_radius_percentage: Schema.Number,
});
export type StoryAreaPosition = typeof StoryAreaPosition.Type;

/** Describes a clickable area on a story media. */
export const StoryArea = Schema.Struct({
	position: StoryAreaPosition,
	type: StoryAreaType,
});
export type StoryArea = typeof StoryArea.Type;

/** Describes a story area pointing to an HTTP or tg:// link. Currently, a story can have up to 3 link areas. */
export const StoryAreaTypeLink = Schema.Struct({
	type: Schema.String,
	url: Schema.String,
});
export type StoryAreaTypeLink = typeof StoryAreaTypeLink.Type;

/** Describes a story area pointing to a location. Currently, a story can have up to 10 location areas. */
export const StoryAreaTypeLocation = Schema.Struct({
	type: Schema.String,
	latitude: Schema.Number,
	longitude: Schema.Number,
	address: Schema.optional(LocationAddress),
});
export type StoryAreaTypeLocation = typeof StoryAreaTypeLocation.Type;

/** Describes a story area pointing to a suggested reaction. Currently, a story can have up to 5 suggested reaction areas. */
export const StoryAreaTypeSuggestedReaction = Schema.Struct({
	type: Schema.String,
	reaction_type: ReactionType,
	is_dark: Schema.optional(Schema.Boolean),
	is_flipped: Schema.optional(Schema.Boolean),
});
export type StoryAreaTypeSuggestedReaction = typeof StoryAreaTypeSuggestedReaction.Type;

/** Describes a story area pointing to a unique gift. Currently, a story can have at most 1 unique gift area. */
export const StoryAreaTypeUniqueGift = Schema.Struct({
	type: Schema.String,
	name: Schema.String,
});
export type StoryAreaTypeUniqueGift = typeof StoryAreaTypeUniqueGift.Type;

/** Describes a story area containing weather information. Currently, a story can have up to 3 weather areas. */
export const StoryAreaTypeWeather = Schema.Struct({
	type: Schema.String,
	temperature: Schema.Number,
	emoji: Schema.String,
	background_color: Schema.Int,
});
export type StoryAreaTypeWeather = typeof StoryAreaTypeWeather.Type;

/** Contains parameters of a post that is being suggested by the bot. */
export const SuggestedPostParameters = Schema.Struct({
	price: Schema.optional(SuggestedPostPrice),
	send_date: Schema.optional(Schema.Int),
});
export type SuggestedPostParameters = typeof SuggestedPostParameters.Type;

/** This object represents a list of boosts added to a chat by a user. */
export const UserChatBoosts = Schema.Struct({
	boosts: Schema.Array(ChatBoost),
});
export type UserChatBoosts = typeof UserChatBoosts.Type;

/** This object represents the audios displayed on a user's profile. */
export const UserProfileAudios = Schema.Struct({
	total_count: Schema.Int,
	audios: Schema.Array(Audio),
});
export type UserProfileAudios = typeof UserProfileAudios.Type;

/** This object represent a user's profile pictures. */
export const UserProfilePhotos = Schema.Struct({
	total_count: Schema.Int,
	photos: Schema.Array(Schema.Array(PhotoSize)),
});
export type UserProfilePhotos = typeof UserProfilePhotos.Type;
