name: Publish
on:
  workflow_dispatch:
jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Nix dev shell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr
          'builtins.currentSystem').default

      - name: Get pnpm store path
        id: pnpm-store
        shell: nix develop -c bash -e {0}
        run: echo "path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        shell: nix develop -c bash -e {0}
        run: pnpm install --frozen-lockfile

      - name: Publish npm package
        shell: nix develop -c bash -e {0}
        run: pnpm publish:npm

  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Nix dev shell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr
          'builtins.currentSystem').default

      - name: Get pnpm store path
        id: pnpm-store
        run: echo "path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
        shell: nix develop -c bash -e {0}

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        shell: nix develop -c bash -e {0}
        run: pnpm install --frozen-lockfile

      - name: Publish JSR package
        shell: nix develop -c bash -e {0}
        run: pnpm publish:jsr
