import { buildErrorExportNames, errorKey, expandMethodErrors } from "./render-errors.ts";
import {
	renderAnnotatedSchemaExpr,
	renderJsDoc,
	renderSchemaExpr,
	methodUsesMultipart,
	type RenderRefStrategy,
} from "./render-type-expr.ts";
import type { Method, Parameter } from "../parse/model.ts";
import type { MethodErrorsDoc } from "./model-errors.ts";

const GENERATED_HEADER = "// Generated by `pnpm codegen` from data/spec. Do not edit manually.";

const methodStrategy: RenderRefStrategy = {
	schemaRef: name => `Objects.${name}`,
	fileSchema: () => "Objects.InputFile",
};

const methodPath = (name: string) => `/${name}`;

const renderPayloadEncodingPipe = (parameters: readonly Parameter[], description: string): string => {
	const encoding = methodUsesMultipart(parameters) ? "HttpApiSchema.asMultipart()" : "HttpApiSchema.asJson()";
	const text = description.trim();
	if (text.length === 0) {
		return `.pipe(Schema.toCodecJson, ${encoding})`;
	}
	return `.pipe(Schema.annotate({ description: ${JSON.stringify(text)} }), Schema.toCodecJson, ${encoding})`;
};

const renderPayloadField = (parameter: Parameter): string => {
	let expr = renderSchemaExpr(parameter.type, methodStrategy);
	if (!parameter.required) {
		expr = `Schema.optional(${expr})`;
	}
	expr = renderAnnotatedSchemaExpr(expr, parameter.description);
	return `${renderJsDoc(parameter.description, "\t\t")}\t\t${parameter.name}: ${expr},`;
};

const renderSuccessSchema = (method: Method): string => {
	const resultExpr = renderSchemaExpr(method.returns, methodStrategy);
	const envelope = `Schema.Struct({\n\t\tok: Schema.Literal(true),\n\t\tresult: ${resultExpr},\n\t})`;
	const pipe =
		method.parameters.length === 0 && method.description.trim().length > 0
			? `.pipe(\n\t\tSchema.annotate({ description: ${JSON.stringify(method.description.trim())} }),\n\t\tSchema.toCodecJson,\n\t\tHttpApiSchema.asJson(),\n\t)`
			: `.pipe(\n\t\tSchema.toCodecJson,\n\t\tHttpApiSchema.asJson(),\n\t)`;
	return `\tsuccess: ${envelope}${pipe},`;
};

const renderErrorField = (
	method: Method,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
	exportNames: ReadonlyMap<string, string>,
): string => {
	const doc = methodErrors.get(method.name);
	if (doc === undefined || doc.errors.length === 0) {
		return "";
	}

	const refs = expandMethodErrors(doc.errors).map(
		error =>
			`Errors.${exportNames.get(errorKey(error))!}.pipe(Schema.toCodecJson, HttpApiSchema.asJson(), HttpApiSchema.status(${error.errorCode}))`,
	);
	return `\terror: [\n\t\t${refs.join(",\n\t\t")},\n\t],`;
};

const renderMethod = (
	method: Method,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
	exportNames: ReadonlyMap<string, string>,
): string => {
	const doc = renderJsDoc(method.description);
	const path = methodPath(method.name);
	const success = renderSuccessSchema(method);
	const errors = renderErrorField(method, methodErrors, exportNames);

	if (method.parameters.length === 0) {
		return `${doc}export const ${method.name} = HttpApiEndpoint.post("${method.name}", "${path}", {\n${success}${errors}\n});`;
	}

	const fields = method.parameters.map(renderPayloadField).join("\n");
	const payload = `\tpayload: Schema.Struct({\n${fields}\n\t})${renderPayloadEncodingPipe(method.parameters, method.description)},`;
	return `${doc}export const ${method.name} = HttpApiEndpoint.post("${method.name}", "${path}", {\n${payload}\n${success}${errors}\n});`;
};

export const renderMethodsModule = (
	methods: readonly Method[],
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): string => {
	const sorted = [...methods].sort((a, b) => a.name.localeCompare(b.name));
	const exportNames = buildErrorExportNames([...methodErrors.values()]);
	const api = `export const TelegramBotApi = HttpApi.make("TelegramBotApi").add(\n\tHttpApiGroup.make("methods", { topLevel: true }).add(\n${sorted
		.map(method => `\t\t${method.name},`)
		.join("\n")}\n\t),\n);`;

	const imports = [
		...(methodErrors.size > 0 ? [`import * as Errors from "./errors.ts";`] : []),
		`import { HttpApi, HttpApiEndpoint, HttpApiGroup, HttpApiSchema } from "effect/unstable/httpapi";`,
		`import * as Schema from "effect/Schema";`,
		`import * as Objects from "./schema.ts";`,
	];

	const sections = [
		GENERATED_HEADER,
		imports.join("\n"),
		...sorted.map(method => renderMethod(method, methodErrors, exportNames)),
		api,
	];

	return `${sections.join("\n\n")}\n`;
};
