import { expandMethodErrors } from "./render-errors.ts";
import { renderInlinedPayloadSchemas } from "./render-payload-schema.ts";
import { methodUsesMultipart } from "./render-type-expr.ts";
import type { Method } from "../parse/model.ts";
import type { MethodErrorsDoc } from "./model-errors.ts";

const GENERATED_HEADER = "// Generated by `pnpm codegen` from spec. Do not edit manually.";

const sortMethods = (methods: readonly Method[]): readonly Method[] =>
	[...methods].sort((a, b) => a.name.localeCompare(b.name));

const renderApiCall = (method: Method): string => {
	if (method.parameters.length === 0) {
		return `apiClient.${method.name}()`;
	}
	if (methodUsesMultipart(method.parameters)) {
		return `encodeToFormData(${method.name}Payload, payload).pipe(Effect.flatMap(form => apiClient.${method.name}({ payload: form })))`;
	}
	return `apiClient.${method.name}({ payload })`;
};

const renderMapError = (method: Method, methodErrors: ReadonlyMap<string, MethodErrorsDoc>): string => {
	const doc = methodErrors.get(method.name);
	if (doc === undefined || doc.errors.length === 0) {
		return "";
	}

	const checks = expandMethodErrors(doc.errors)
		.map(
			error =>
				`\t\t\tif ("error_code" in error && error.error_code === ${error.errorCode} && error.description === ${JSON.stringify(error.description)}) return new Errors.${error.tag}(error);`,
		)
		.join("\n");

	return [`\t\t\tEffect.mapError(error => {`, checks, `\t\t\t\treturn error;`, `\t\t\t}),`].join("\n");
};

const renderMethodImpl = (method: Method, methodErrors: ReadonlyMap<string, MethodErrorsDoc>): string => {
	const signature =
		method.parameters.length === 0 ? `const ${method.name} = (() =>` : `const ${method.name} = ((payload) =>`;

	return [
		`\t\t\t${signature}`,
		`\t\t\t\t${renderApiCall(method)}.pipe(`,
		`\t\t\t\tEffect.map(response => response.result),`,
		renderMapError(method, methodErrors),
		`\t\t\t)`,
		`\t\t\t) as TelegramClientService["${method.name}"];`,
	].join("\n");
};

export const renderTelegramModule = (
	methods: readonly Method[],
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): string => {
	const sorted = sortMethods(methods);
	const hasMultipart = methods.some(method => method.parameters.length > 0 && methodUsesMultipart(method.parameters));
	const inlinedPayloadSchemas = renderInlinedPayloadSchemas(methods);

	return [
		GENERATED_HEADER,
		`import * as Effect from "effect/Effect";`,
		`import * as Layer from "effect/Layer";`,
		`import * as HttpApiClient from "effect/unstable/httpapi/HttpApiClient";`,
		`import * as Errors from "../errors.ts";`,
		`import { TelegramBotApi } from "../http-api.ts";`,
		...(hasMultipart ? [`import * as Schema from "effect/Schema";`, `import * as Objects from "../schema.ts";`] : []),
		`import { TelegramClient } from "./service.ts";`,
		...(hasMultipart ? [`import { encodeToFormData } from "./to-form.ts";`] : []),
		``,
		`const BASE_URL = "https://api.telegram.org";`,
		``,
		`type TelegramClientService = (typeof TelegramClient)["Service"];`,
		``,
		inlinedPayloadSchemas,
		`/**`,
		` * Builds a {@link TelegramClient} layer for the given bot token by unwrapping`,
		` * wire responses from the underlying HTTP client.`,
		` */`,
		`export const withToken = (token: string) =>`,
		`\tLayer.effect(`,
		`\t\tTelegramClient,`,
		`\t\tEffect.gen(function* () {`,
		`\t\t\tconst apiClient = yield* HttpApiClient.make(TelegramBotApi, { baseUrl: \`\${BASE_URL}/bot\${token}\` });`,
		``,
		...sorted.map(method => renderMethodImpl(method, methodErrors)),
		``,
		`\t\t\treturn { ${sorted.map(method => method.name).join(", ")} };`,
		`\t\t}),`,
		`\t);`,
		``,
	].join("\n");
};
