import { methodErrorTags } from "./render-errors.ts";
import { collectRefs, renderJsDoc, renderTsType } from "./render-type-expr.ts";
import type { Method, Parameter } from "../parse/model.ts";
import type { MethodErrorsDoc } from "./model-errors.ts";

const GENERATED_HEADER = "// Generated by `pnpm codegen` from spec. Do not edit manually.";

const renderPayloadField = (parameter: Parameter, knownNames: ReadonlySet<string>): string => {
	const type = renderTsType(parameter.type, knownNames);
	const member = parameter.required
		? `\treadonly ${parameter.name}: ${type};`
		: `\treadonly ${parameter.name}?: ${type === "unknown" ? "unknown" : `${type} | undefined`};`;
	return `${renderJsDoc(parameter.description, "\t\t")}\t\t${member}`;
};

const renderPayloadType = (parameters: readonly Parameter[], knownNames: ReadonlySet<string>): string => {
	if (parameters.length === 0) {
		return "";
	}
	const fields = parameters.map(parameter => renderPayloadField(parameter, knownNames)).join("\n");
	return `{\n${fields}\n\t}`;
};

const renderErrorUnion = (method: string, methodErrors: ReadonlyMap<string, MethodErrorsDoc>): string => {
	const tags = methodErrorTags(method, methodErrors);
	const members = [...tags.map(tag => `Errors.${tag}`), "Errors.TelegramApiError", "HttpClientError.HttpClientError"];
	return members.join(" | ");
};

const renderEffectType = (success: string, errors: string): string => {
	const successType = success === "true" || success === "false" ? `(${success})` : success;
	return `Effect.Effect<${successType}, ${errors}>`;
};

const renderMethod = (
	method: Method,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
	knownNames: ReadonlySet<string>,
): string => {
	const doc = renderJsDoc(method.description, "\t");
	const success = renderTsType(method.returns, knownNames);
	const errors = renderErrorUnion(method.name, methodErrors);
	const effect = renderEffectType(success, errors);

	if (method.parameters.length === 0) {
		return `${doc}\treadonly ${method.name}: () => ${effect};`;
	}

	const payload = renderPayloadType(method.parameters, knownNames);
	return `${doc}\treadonly ${method.name}: (payload: ${payload}) => ${effect};`;
};

const collectObjectImports = (methods: readonly Method[], knownNames: ReadonlySet<string>): readonly string[] => {
	const refs = new Set<string>();
	for (const method of methods) {
		collectRefs(method.returns, refs);
		for (const parameter of method.parameters) {
			collectRefs(parameter.type, refs);
		}
	}
	return [...refs].filter(name => knownNames.has(name)).sort((a, b) => a.localeCompare(b));
};

export const renderTelegramClientModule = (
	methods: readonly Method[],
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
	knownNames: ReadonlySet<string>,
): string => {
	const sorted = [...methods].sort((a, b) => a.name.localeCompare(b.name));
	const objectImports = collectObjectImports(sorted, knownNames);
	const objectImportLine =
		objectImports.length === 0 ? "" : `import type { ${objectImports.join(", ")} } from "../schema.ts";\n`;

	const sections = [
		GENERATED_HEADER,
		`import * as Context from "effect/Context";`,
		`import * as Effect from "effect/Effect";`,
		`import type * as Errors from "../errors.ts";`,
		objectImportLine.trimEnd(),
		`import type * as HttpClientError from "effect/unstable/http/HttpClientError";`,
		``,
		`export class TelegramClient extends Context.Service<TelegramClient, {`,
		...sorted.map(method => renderMethod(method, methodErrors, knownNames)),
		`}>()("TelegramClient") {}`,
	];

	return sections.filter(line => line.length > 0).join("\n") + "\n";
};
