import { docUrlFromSlug } from "../document.ts";
import { analyzeDependencies } from "./dependency-graph.ts";
import {
	collectRefs,
	INPUT_FILE_TYPE,
	renderAnnotatedSchemaExpr,
	renderJsDoc,
	renderSchemaExpr,
	renderTsType,
	type RenderRefStrategy,
} from "./render-type-expr.ts";
import type { Field, ObjectType, SpecType, UnionType } from "../parse/model.ts";

const GENERATED_HEADER = "// Generated by `pnpm codegen` from spec. Do not edit manually.";

/** Reference strategy for a single object: cycle members are deferred via `Schema.suspend`. */
const strategyFor = (scc: ReadonlySet<string>): RenderRefStrategy => ({
	schemaRef: name => (scc.has(name) ? `Schema.suspend((): Schema.Codec<${name}> => ${name})` : name),
	fileSchema: () => INPUT_FILE_TYPE,
});

const renderSchemaField = (field: Field, strategy: RenderRefStrategy): string => {
	let expr = renderSchemaExpr(field.type, strategy);
	if (!field.required) {
		expr = `Schema.optional(${expr})`;
	}
	expr = renderAnnotatedSchemaExpr(expr, field.description);
	return `${renderJsDoc(field.description, "\t")}\t${field.name}: ${expr},`;
};

const renderInterfaceField = (field: Field, knownNames: ReadonlySet<string>): string => {
	const type = renderTsType(field.type, knownNames);
	const member = field.required
		? `\treadonly ${field.name}: ${type};`
		: `\treadonly ${field.name}?: ${type === "unknown" ? "unknown" : `${type} | undefined`};`;
	return `${renderJsDoc(field.description, "\t")}${member}`;
};

const renderSchema = (object: ObjectType, strategy: RenderRefStrategy): string => {
	const body = object.fields.map(field => renderSchemaField(field, strategy)).join("\n");
	const struct = body.length === 0 ? "Schema.Struct({})" : `Schema.Struct({\n${body}\n})`;
	return `export const ${object.name} = ${renderAnnotatedSchemaExpr(struct, object.description)};`;
};

const renderStructuralType = (object: ObjectType, knownNames: ReadonlySet<string>): string => {
	const body = object.fields.map(field => renderInterfaceField(field, knownNames)).join("\n");
	return body.length === 0 ? `export type ${object.name} = {};` : `export type ${object.name} = {\n${body}\n};`;
};

const renderObject = (
	object: ObjectType,
	scc: ReadonlySet<string>,
	recursive: boolean,
	knownNames: ReadonlySet<string>,
): string => {
	const doc = renderJsDoc(object.description, "", docUrlFromSlug(object.slug));
	const schema = renderSchema(object, strategyFor(scc));

	// Recursive schemas cannot have their type inferred (`typeof` would reference
	// itself), so the type is declared structurally. Everything else infers.
	if (recursive) {
		return `${doc}${renderStructuralType(object, knownNames)}\n${schema}`;
	}
	return `${doc}${schema}\nexport type ${object.name} = typeof ${object.name}.Type;`;
};

const renderUnion = (union: UnionType, scc: ReadonlySet<string>): string => {
	const strategy = strategyFor(scc);
	const members = union.variants.map(variant => strategy.schemaRef(variant.name)).join(", ");
	const expr = `Schema.Union([${members}])`;
	const see = [docUrlFromSlug(union.slug), ...union.variants.map(variant => docUrlFromSlug(variant.slug))];
	const doc = renderJsDoc(union.description, "", see);
	return `${doc}export const ${union.name} = ${renderAnnotatedSchemaExpr(expr, union.description)};\nexport type ${union.name} = typeof ${union.name}.Type;`;
};

const renderPlaceholder = (name: string): string =>
	`// TODO: schema not yet generated from the spec.\nexport const ${name} = Schema.Unknown;\nexport type ${name} = typeof ${name}.Type;`;

export interface RenderObjectsResult {
	readonly source: string;
	readonly placeholders: readonly string[];
}

export const renderObjectsModule = (
	objects: readonly ObjectType[],
	unions: readonly UnionType[],
	extraRefs: Iterable<string>,
	methodNames: ReadonlySet<string> = new Set(),
): RenderObjectsResult => {
	const generated = new Set([...objects.map(object => object.name), ...unions.map(union => union.name)]);

	const referenced = new Set<string>(extraRefs);
	for (const object of objects) {
		for (const field of object.fields) {
			collectRefs(field.type, referenced);
		}
	}

	const placeholders = [...referenced]
		.filter(name => !generated.has(name) && name !== INPUT_FILE_TYPE && !methodNames.has(name))
		.sort();
	const knownNames = new Set([...generated, INPUT_FILE_TYPE]);

	const { order, sccOf, recursive } = analyzeDependencies(objects, unions);
	const byName = new Map<string, SpecType>([
		...objects.map(object => [object.name, object] as const),
		...unions.map(union => [union.name, union] as const),
	]);

	const sections = [
		GENERATED_HEADER,
		`import * as Schema from "effect/Schema";`,
		`${renderJsDoc("A file to be uploaded to Telegram via multipart/form-data.")}export const ${INPUT_FILE_TYPE} = ${renderAnnotatedSchemaExpr("Schema.Uint8Array", "A file to be uploaded to Telegram via multipart/form-data.")};\nexport type ${INPUT_FILE_TYPE} = typeof ${INPUT_FILE_TYPE}.Type;`,
		...placeholders.map(renderPlaceholder),
		...order.map(name => {
			const spec = byName.get(name)!;
			const scc = sccOf.get(name)!;
			return spec.kind === "union" ? renderUnion(spec, scc) : renderObject(spec, scc, recursive.has(name), knownNames);
		}),
	];

	return { source: `${sections.join("\n\n")}\n`, placeholders };
};
