import { HTTP_STATUS_ERRORS, HTTP_STATUS_ERRORS_BY_CODE } from "./http-status-errors.ts";
import { renderJsDoc } from "./render-type-expr.ts";
import type { MethodErrorsDoc } from "./model-errors.ts";

const GENERATED_HEADER =
	"// Generated by `pnpm codegen` from spec/errors/errors.json and spec/errors/{method}.json. Do not edit manually.";

export const statusErrorSchemaName = (tag: string): string => `${tag}Error`;

const renderStatusErrorClass = (tag: string, errorCode: number, when?: string): string => {
	const doc = when === undefined ? "" : renderJsDoc(when).trimEnd();
	return [
		doc,
		`export class ${tag} extends Data.TaggedError("${tag}")<{`,
		`\treadonly ok: false;`,
		`\treadonly error_code: ${errorCode};`,
		`\treadonly description: string;`,
		`}> {}`,
	].join("\n");
};

const renderStatusErrorSchema = (tag: string, errorCode: number, when?: string): string => {
	const exportName = statusErrorSchemaName(tag);
	const doc = when === undefined ? "" : renderJsDoc(when).trimEnd();
	return [
		doc,
		`export const ${exportName} = Schema.Struct({`,
		`\tok: Schema.Literal(false),`,
		`\terror_code: Schema.Literal(${errorCode}),`,
		`\tdescription: Schema.String,`,
		`});`,
	].join("\n");
};

const renderTelegramApiErrorClass = (): string =>
	[
		`/**`,
		` * Raised when Telegram responds with \`{ "ok": false }\` and the failure is not documented for the method.`,
		` */`,
		`export class TelegramApiError extends Data.TaggedError("TelegramApiError")<{`,
		`\treadonly errorCode: number;`,
		`\treadonly description: string;`,
		`}> {}`,
	].join("\n");

const renderTelegramApiFailureSchema = (): string =>
	[
		`/**`,
		` * Catch-all wire schema for undocumented \`{ "ok": false }\` responses.`,
		` */`,
		`export const TelegramApiFailureError = Schema.Struct({`,
		`\tok: Schema.Literal(false),`,
		`\terror_code: Schema.Number,`,
		`\tdescription: Schema.String,`,
		`});`,
	].join("\n");

export const renderErrorsModule = (): string =>
	[
		GENERATED_HEADER,
		`import * as Data from "effect/Data";`,
		`import * as Schema from "effect/Schema";`,
		renderTelegramApiErrorClass(),
		...HTTP_STATUS_ERRORS.flatMap(error => [
			renderStatusErrorClass(error.tag, error.errorCode, error.when),
			renderStatusErrorSchema(error.tag, error.errorCode, error.when),
		]),
		renderTelegramApiFailureSchema(),
	].join("\n\n") + "\n";

/** Unique status errors documented for a method, deduped by tag. */
export const methodStatusErrors = (
	method: string,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): readonly { readonly tag: string; readonly errorCode: number }[] => {
	const doc = methodErrors.get(method);
	if (doc === undefined) {
		return [];
	}
	const byTag = new Map<string, number>();
	for (const error of doc.errors) {
		byTag.set(error.tag, error.errorCode);
	}
	return [...byTag.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([tag, errorCode]) => ({ tag, errorCode }));
};

/** Unique status error tags documented for a method (for TelegramClient error unions). */
export const methodStatusTags = (
	method: string,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): readonly string[] => methodStatusErrors(method, methodErrors).map(error => error.tag);

/** Unique status error codes documented for a method (for HttpApi error schemas). */
export const methodStatusCodes = (
	method: string,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): readonly number[] => methodStatusErrors(method, methodErrors).map(error => error.errorCode);

export const methodStatusErrorRefs = (
	method: string,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): readonly string[] =>
	methodStatusErrors(method, methodErrors).map(error => `Errors.${statusErrorSchemaName(error.tag)}`);

export const statusTagForCode = (errorCode: number): string => {
	const error = HTTP_STATUS_ERRORS_BY_CODE.get(errorCode);
	if (error === undefined) {
		throw new Error(`No HTTP status error defined for code ${errorCode}`);
	}
	return error.tag;
};
