const GENERATED_HEADER = "// Generated by `pnpm codegen` from data/spec. Do not edit manually.";

export const renderIndexModule = (hasMethodErrors: boolean): string => {
	const exports = [
		`export * as Client from "./Client.ts";`,
		...(hasMethodErrors ? [`export * as Errors from "./Errors.ts";`] : []),
		`export * as Methods from "./Methods.ts";`,
		`export * as Objects from "./Objects.ts";`,
	];

	return [GENERATED_HEADER, ...exports].join("\n") + "\n";
};
