const GENERATED_HEADER = "// Generated by `pnpm codegen` from data/spec. Do not edit manually.";

export const renderIndexModule = (_hasMethodErrors: boolean): string => {
	const exports = [
		`export * as Telegram from "./Telegram.ts";`,
		`export { withToken } from "./Telegram.ts";`,
		`export * as Errors from "./Errors.ts";`,
		`export * as Methods from "./Methods.ts";`,
		`export * as Objects from "./Objects.ts";`,
		`export * as TelegramClient from "./TelegramClient.ts";`,
		`export { TelegramApiError } from "./TelegramApiError.ts";`,
	];

	return [GENERATED_HEADER, ...exports].join("\n") + "\n";
};
