const GENERATED_HEADER = "// Generated by `pnpm codegen` from data/spec. Do not edit manually.";

export const renderIndexModule = (): string =>
	[
		GENERATED_HEADER,
		`export * as Client from "./Client.ts";`,
		`export * as Methods from "./Methods.ts";`,
		`export * as Objects from "./Objects.ts";`,
	].join("\n") + "\n";
