import type { MethodError, MethodErrorsDoc } from "./model-errors.ts";

const GENERATED_HEADER =
	"// Generated by `pnpm codegen` from errors/errors.json and errors/{method}.json. Do not edit manually.";

const renderErrorClass = (error: MethodError): string => {
	const doc = error.when === undefined ? "" : `/** ${error.when.replace(/\*\//g, "*\\/")} */\n`;
	return [
		doc,
		`export class ${error.tag} extends Data.TaggedError("${error.tag}")<{`,
		`\treadonly description: string;`,
		`}> {}`,
		``,
		`export const ${error.tag}Error = Schema.TaggedStruct("${error.tag}", {`,
		`\tdescription: Schema.String,`,
		`});`,
	].join("\n");
};

const collectUniqueErrors = (docs: readonly MethodErrorsDoc[]): MethodError[] => {
	const byTag = new Map<string, MethodError>();
	for (const doc of docs) {
		for (const error of doc.errors) {
			const existing = byTag.get(error.tag);
			if (existing !== undefined) {
				if (existing.errorCode !== error.errorCode) {
					throw new Error(
						`Error tag ${error.tag} has conflicting errorCode: ${existing.errorCode} vs ${error.errorCode}`,
					);
				}
				continue;
			}
			byTag.set(error.tag, error);
		}
	}
	return [...byTag.values()].sort((a, b) => a.tag.localeCompare(b.tag));
};

const renderMethodErrorsRegistry = (docs: readonly MethodErrorsDoc[]): string => {
	const entries = [...docs]
		.sort((a, b) => a.method.localeCompare(b.method))
		.map(doc => {
			const cases = doc.errors
				.map(
					error =>
						`\t\t{ errorCode: ${error.errorCode}, description: ${JSON.stringify(error.description)}, error: ${error.tag} }`,
				)
				.join(",\n");
			return `\t${doc.method}: [\n${cases},\n\t]`;
		})
		.join(",\n");

	return [`export const methodErrors = {`, entries, `} as const;`].join("\n");
};

export const renderErrorsModule = (docs: readonly MethodErrorsDoc[]): string => {
	if (docs.length === 0) {
		return `${GENERATED_HEADER}\n`;
	}

	const unique = collectUniqueErrors(docs);
	return (
		[
			GENERATED_HEADER,
			`import * as Data from "effect/Data";`,
			`import * as Schema from "effect/Schema";`,
			...unique.map(renderErrorClass),
			renderMethodErrorsRegistry(docs),
		].join("\n\n") + "\n"
	);
};

export const methodRpcError = (method: string, methodErrors: ReadonlyMap<string, MethodErrorsDoc>): string => {
	const doc = methodErrors.get(method);
	if (doc === undefined) {
		return "";
	}

	const refs = doc.errors.map(error => `Errors.${error.tag}Error`);
	return refs.length === 1 ? refs[0]! : `Schema.Union([${refs.join(", ")}])`;
};
