import { expandError } from "./model-errors.ts";
import { renderJsDoc } from "./render-type-expr.ts";
import type { MethodError, MethodErrorsDoc } from "./model-errors.ts";

const GENERATED_HEADER =
	"// Generated by `pnpm codegen` from errors/errors.json and errors/{method}.json. Do not edit manually.";

export type ErrorInstance = MethodErrorsDoc["errors"][number];

export const errorKey = (error: ErrorInstance): string => `${error.tag}|${error.errorCode}|${error.description}`;

/** Stable schema export names for each unique `(tag, errorCode, description)` triple. */
export const buildErrorExportNames = (docs: readonly MethodErrorsDoc[]): ReadonlyMap<string, string> => {
	const tagCounts = new Map<string, number>();
	const exportNames = new Map<string, string>();
	const sorted = [...docs]
		.flatMap(doc => doc.errors)
		.sort((a, b) => a.tag.localeCompare(b.tag) || a.description.localeCompare(b.description));

	for (const error of sorted) {
		const key = errorKey(error);
		if (exportNames.has(key)) {
			continue;
		}
		const count = (tagCounts.get(error.tag) ?? 0) + 1;
		tagCounts.set(error.tag, count);
		exportNames.set(key, count === 1 ? `${error.tag}Error` : `${error.tag}Error${count}`);
	}
	return exportNames;
};

const collectUniqueTags = (docs: readonly MethodErrorsDoc[]): ErrorInstance[] => {
	const byTag = new Map<string, ErrorInstance>();
	for (const doc of docs) {
		for (const error of doc.errors) {
			const existing = byTag.get(error.tag);
			if (existing !== undefined) {
				if (existing.errorCode !== error.errorCode) {
					throw new Error(
						`Error tag ${error.tag} has conflicting errorCode: ${existing.errorCode} vs ${error.errorCode}`,
					);
				}
				continue;
			}
			byTag.set(error.tag, error);
		}
	}
	return [...byTag.values()].sort((a, b) => a.tag.localeCompare(b.tag));
};

const collectUniqueSchemas = (docs: readonly MethodErrorsDoc[]): ErrorInstance[] => {
	const byKey = new Map<string, ErrorInstance>();
	for (const doc of docs) {
		for (const error of doc.errors) {
			byKey.set(errorKey(error), error);
		}
	}
	return [...byKey.values()].sort((a, b) => a.tag.localeCompare(b.tag) || a.description.localeCompare(b.description));
};

const renderErrorClass = (error: ErrorInstance): string => {
	const doc = error.when === undefined ? "" : renderJsDoc(error.when).trimEnd();
	return [
		doc,
		`export class ${error.tag} extends Data.TaggedError("${error.tag}")<{`,
		`\treadonly ok: false;`,
		`\treadonly error_code: ${error.errorCode};`,
		`\treadonly description: string;`,
		`}> {}`,
	].join("\n");
};

const renderErrorSchema = (error: ErrorInstance, exportName: string): string => {
	const doc = error.when === undefined ? "" : renderJsDoc(error.when).trimEnd();
	return [
		doc,
		`export const ${exportName} = Schema.Struct({`,
		`\tok: Schema.Literal(false),`,
		`\terror_code: Schema.Literal(${error.errorCode}),`,
		`\tdescription: Schema.Literal(${JSON.stringify(error.description)}),`,
		`});`,
	].join("\n");
};

const renderTelegramApiErrorClass = (): string =>
	[
		`/**`,
		` * Raised when Telegram responds with \`{ "ok": false }\` and the failure is not documented for the method.`,
		` */`,
		`export class TelegramApiError extends Data.TaggedError("TelegramApiError")<{`,
		`\treadonly errorCode: number;`,
		`\treadonly description: string;`,
		`}> {}`,
	].join("\n");

export const renderErrorsModule = (docs: readonly MethodErrorsDoc[]): string => {
	const exportNames = docs.length > 0 ? buildErrorExportNames(docs) : new Map<string, string>();
	const classes = docs.length > 0 ? collectUniqueTags(docs) : [];
	const schemas = docs.length > 0 ? collectUniqueSchemas(docs) : [];

	return (
		[
			GENERATED_HEADER,
			`import * as Data from "effect/Data";`,
			...(docs.length > 0 ? [`import * as Schema from "effect/Schema";`] : []),
			renderTelegramApiErrorClass(),
			...classes.map(renderErrorClass),
			...schemas.map(error => renderErrorSchema(error, exportNames.get(errorKey(error))!)),
		].join("\n\n") + "\n"
	);
};

export const methodErrorRefs = (
	method: string,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
	exportNames: ReadonlyMap<string, string>,
): readonly string[] => {
	const doc = methodErrors.get(method);
	if (doc === undefined) {
		return [];
	}
	return expandMethodErrors(doc.errors).map(error => `Errors.${exportNames.get(errorKey(error))!}`);
};

/** Expands method error entries including description variants. */
export const expandMethodErrors = (errors: readonly MethodError[]): readonly ErrorInstance[] =>
	errors.flatMap(expandError);

/** Unique error class tags documented for a method (for TelegramClient error unions). */
export const methodErrorTags = (
	method: string,
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): readonly string[] => {
	const doc = methodErrors.get(method);
	if (doc === undefined) {
		return [];
	}
	return [...new Set(doc.errors.map(error => error.tag))].sort((a, b) => a.localeCompare(b));
};
