import { analyzeDependencies } from "./dependency-graph.ts";
import {
	collectRefs,
	INPUT_FILE_TYPE,
	renderSchemaExpr,
	renderTsType,
	type RenderRefStrategy,
} from "./render-type-expr.ts";
import type { Field, ObjectType } from "../parse/model.ts";

const GENERATED_HEADER = "// Generated by `pnpm codegen` from data/spec. Do not edit manually.";

const jsDoc = (description: string): string => {
	const text = description.trim().replace(/\*\//g, "*\\/");
	return text.length === 0 ? "" : `/** ${text} */\n`;
};

/** Reference strategy for a single object: cycle members are deferred via `Schema.suspend`. */
const strategyFor = (scc: ReadonlySet<string>): RenderRefStrategy => ({
	schemaRef: name => (scc.has(name) ? `Schema.suspend((): Schema.Codec<${name}> => ${name})` : name),
	fileSchema: () => INPUT_FILE_TYPE,
});

const renderSchemaField = (field: Field, strategy: RenderRefStrategy): string => {
	const expr = renderSchemaExpr(field.type, strategy);
	return field.required ? `\t${field.name}: ${expr},` : `\t${field.name}: Schema.optional(${expr}),`;
};

const renderInterfaceField = (field: Field, knownNames: ReadonlySet<string>): string => {
	const type = renderTsType(field.type, knownNames);
	if (field.required) {
		return `\treadonly ${field.name}: ${type};`;
	}
	// `unknown | undefined` collapses to `unknown`, so skip the redundant union.
	return `\treadonly ${field.name}?: ${type === "unknown" ? "unknown" : `${type} | undefined`};`;
};

const renderSchema = (object: ObjectType, strategy: RenderRefStrategy): string => {
	const body = object.fields.map(field => renderSchemaField(field, strategy)).join("\n");
	return body.length === 0
		? `export const ${object.name} = Schema.Struct({});`
		: `export const ${object.name} = Schema.Struct({\n${body}\n});`;
};

const renderStructuralType = (object: ObjectType, knownNames: ReadonlySet<string>): string => {
	const body = object.fields.map(field => renderInterfaceField(field, knownNames)).join("\n");
	return body.length === 0 ? `export type ${object.name} = {};` : `export type ${object.name} = {\n${body}\n};`;
};

const renderObject = (
	object: ObjectType,
	scc: ReadonlySet<string>,
	recursive: boolean,
	knownNames: ReadonlySet<string>,
): string => {
	const doc = jsDoc(object.description);
	const schema = renderSchema(object, strategyFor(scc));

	// Recursive schemas cannot have their type inferred (`typeof` would reference
	// itself), so the type is declared structurally. Everything else infers.
	if (recursive) {
		return `${doc}${renderStructuralType(object, knownNames)}\n${schema}`;
	}
	return `${doc}${schema}\nexport type ${object.name} = typeof ${object.name}.Type;`;
};

const renderPlaceholder = (name: string): string =>
	`// TODO: union/polymorphic type not yet generated from the spec.\nexport const ${name} = Schema.Unknown;\nexport type ${name} = typeof ${name}.Type;`;

export interface RenderObjectsResult {
	readonly source: string;
	readonly placeholders: readonly string[];
}

export const renderObjectsModule = (
	objects: readonly ObjectType[],
	extraRefs: Iterable<string>,
	methodNames: ReadonlySet<string> = new Set(),
): RenderObjectsResult => {
	const generated = new Set(objects.map(object => object.name));

	const referenced = new Set<string>(extraRefs);
	for (const object of objects) {
		for (const field of object.fields) {
			collectRefs(field.type, referenced);
		}
	}

	const placeholders = [...referenced]
		.filter(name => !generated.has(name) && name !== INPUT_FILE_TYPE && !methodNames.has(name))
		.sort();
	const knownNames = new Set([...generated, INPUT_FILE_TYPE]);

	const { order, sccOf, recursive } = analyzeDependencies(objects);
	const byName = new Map(objects.map(object => [object.name, object]));

	const sections = [
		GENERATED_HEADER,
		`import * as Schema from "effect/Schema";`,
		`/** A file to be uploaded to Telegram via multipart/form-data. */\nexport const ${INPUT_FILE_TYPE} = Schema.Uint8Array;\nexport type ${INPUT_FILE_TYPE} = typeof ${INPUT_FILE_TYPE}.Type;`,
		...placeholders.map(renderPlaceholder),
		...order.map(name => renderObject(byName.get(name)!, sccOf.get(name)!, recursive.has(name), knownNames)),
	];

	return { source: `${sections.join("\n\n")}\n`, placeholders };
};
