import { methodHttpApiError } from "./render-errors.ts";
import {
	renderAnnotatedSchemaExpr,
	renderJsDoc,
	renderSchemaExpr,
	type RenderRefStrategy,
} from "./render-type-expr.ts";
import type { Method, Parameter } from "../parse/model.ts";
import type { MethodErrorsDoc } from "./model-errors.ts";

const GENERATED_HEADER = "// Generated by `pnpm codegen` from data/spec. Do not edit manually.";

const methodStrategy: RenderRefStrategy = {
	schemaRef: name => `Objects.${name}`,
	fileSchema: () => "Objects.InputFile",
};

/** Telegram URLs are `/bot<token>/<method>` (no slash between `bot` and the token). */
const methodPath = (name: string) => `/bot:token/${name}`;

const renderPayloadField = (parameter: Parameter): string => {
	let expr = renderSchemaExpr(parameter.type, methodStrategy);
	if (!parameter.required) {
		expr = `Schema.optional(${expr})`;
	}
	expr = renderAnnotatedSchemaExpr(expr, parameter.description);
	return `${renderJsDoc(parameter.description, "\t\t")}\t\t${parameter.name}: ${expr},`;
};

const renderMethod = (method: Method, methodErrors: ReadonlyMap<string, MethodErrorsDoc>): string => {
	const doc = renderJsDoc(method.description);
	const path = methodPath(method.name);
	const params = `\tparams: { token: Schema.String },`;
	const errorField = methodErrors.has(method.name)
		? `\n\terror: ${methodHttpApiError(method.name, methodErrors)},`
		: "";
	const successExpr = renderSchemaExpr(method.returns, methodStrategy);
	const success =
		method.parameters.length === 0
			? `\tsuccess: ${renderAnnotatedSchemaExpr(successExpr, method.description)},`
			: `\tsuccess: ${successExpr},`;

	if (method.parameters.length === 0) {
		return `${doc}export const ${method.name} = HttpApiEndpoint.post("${method.name}", "${path}", {\n${params}\n${success}${errorField}\n});`;
	}

	const fields = method.parameters.map(renderPayloadField).join("\n");
	const payload = `\tpayload: ${renderAnnotatedSchemaExpr(`Schema.Struct({\n${fields}\n\t})`, method.description)},`;
	return `${doc}export const ${method.name} = HttpApiEndpoint.post("${method.name}", "${path}", {\n${params}\n${payload}\n${success}${errorField}\n});`;
};

export const renderMethodsModule = (
	methods: readonly Method[],
	methodErrors: ReadonlyMap<string, MethodErrorsDoc>,
): string => {
	const sorted = [...methods].sort((a, b) => a.name.localeCompare(b.name));
	const api = `export const TelegramBotApi = HttpApi.make("TelegramBotApi").add(\n\tHttpApiGroup.make("methods", { topLevel: true }).add(\n${sorted
		.map(method => `\t\t${method.name},`)
		.join("\n")}\n\t),\n);`;

	const imports = [
		...(methodErrors.size > 0 ? [`import * as Errors from "./Errors.ts";`] : []),
		`import { HttpApi, HttpApiEndpoint, HttpApiGroup } from "effect/unstable/httpapi";`,
		`import * as Schema from "effect/Schema";`,
		`import * as Objects from "./Objects.ts";`,
	];

	const sections = [
		GENERATED_HEADER,
		imports.join("\n"),
		...sorted.map(method => renderMethod(method, methodErrors)),
		api,
	];

	return `${sections.join("\n\n")}\n`;
};
